-- Inserting data into Conference
INSERT INTO
    Conference (
        ConferenceID,
        Name,
        SeriesName,
        Date,
        Location,
        Ranking,
        AcceptanceRate,
        SubmissionDeadline,
        ReviewProcess,
        VirtualHybridPhysical
    )
VALUES
    (
        1,
        'International Conference on Artificial Intelligence',
        'AI Summit',
        '2024-03-15',
        'Tokyo, Japan',
        15,
        0.25,
        '2023-12-01',
        'Double-blind',
        'Hybrid'
    ),
    (
        2,
        'Asian Conference on Machine Learning',
        'ACML',
        '2024-04-10',
        'Seoul, South Korea',
        22,
        0.2,
        '2023-11-20',
        'Single-blind',
        'Physical'
    ),
    (
        3,
        'Asia-Pacific Conference on Computer Vision',
        'APCCV',
        '2024-05-05',
        'Beijing, China',
        30,
        0.18,
        '2023-12-15',
        'Double-blind',
        'Virtual'
    ),
    (
        4,
        'International Symposium on Robotics',
        'ISR',
        '2024-06-12',
        'Singapore',
        35,
        0.22,
        '2024-01-10',
        'Single-blind',
        'Hybrid'
    ),
    (
        5,
        'Conference on Data Science and Analytics',
        'DSA Asia',
        '2024-07-20',
        'Bangkok, Thailand',
        40,
        0.27,
        '2024-02-05',
        'Double-blind',
        'Physical'
    ),
    (
        6,
        'Asian Conference on Software Engineering',
        'ACSE',
        '2024-08-18',
        'Kuala Lumpur, Malaysia',
        45,
        0.23,
        '2024-03-01',
        'Single-blind',
        'Hybrid'
    ),
    (
        7,
        'International Conference on Cybersecurity',
        'ICCS',
        '2024-09-25',
        'Mumbai, India',
        50,
        0.19,
        '2024-04-15',
        'Double-blind',
        'Virtual'
    ),
    (
        8,
        'Asian Symposium on Human-Computer Interaction',
        'AS-HCI',
        '2024-10-30',
        'Jakarta, Indonesia',
        55,
        0.21,
        '2024-05-20',
        'Single-blind',
        'Physical'
    ),
    (
        9,
        'Asia-Pacific Conference on Information Systems',
        'APCIS',
        '2024-11-15',
        'Hanoi, Vietnam',
        60,
        0.29,
        '2024-06-10',
        'Double-blind',
        'Hybrid'
    ),
    (
        10,
        'International Conference on Quantum Computing',
        'ICQC',
        '2024-12-05',
        'Hong Kong',
        65,
        0.24,
        '2024-07-01',
        'Single-blind',
        'Virtual'
    ),
    (
        11,
        'Asian Conference on Natural Language Processing',
        'ACNLP',
        '2024-01-18',
        'Manila, Philippines',
        70,
        0.28,
        '2023-09-15',
        'Double-blind',
        'Physical'
    ),
    (
        12,
        'Asia-Pacific Symposium on Internet of Things',
        'APSIoT',
        '2024-02-22',
        'Taipei, Taiwan',
        75,
        0.26,
        '2023-10-05',
        'Single-blind',
        'Hybrid'
    ),
    (
        13,
        'International Conference on Big Data',
        'ICBD',
        '2024-03-30',
        'Shanghai, China',
        80,
        0.17,
        '2023-11-01',
        'Double-blind',
        'Virtual'
    ),
    (
        14,
        'Asian Symposium on Computer Networks',
        'ASCN',
        '2024-04-25',
        'Ho Chi Minh City, Vietnam',
        85,
        0.2,
        '2023-11-20',
        'Single-blind',
        'Physical'
    ),
    (
        15,
        'Asia-Pacific Conference on Embedded Systems',
        'APCES',
        '2024-05-18',
        'Chennai, India',
        90,
        0.3,
        '2023-12-10',
        'Double-blind',
        'Hybrid'
    ),
    (
        16,
        'International Symposium on Bioinformatics',
        'ISB',
        '2024-06-22',
        'Osaka, Japan',
        95,
        0.27,
        '2024-01-15',
        'Single-blind',
        'Virtual'
    ),
    (
        17,
        'Conference on Computational Linguistics',
        'CCL Asia',
        '2024-07-28',
        'Bangkok, Thailand',
        100,
        0.22,
        '2024-02-10',
        'Double-blind',
        'Physical'
    ),
    (
        18,
        'Asian Conference on Digital Libraries',
        'ACDL',
        '2024-08-14',
        'Singapore',
        10,
        0.26,
        '2024-03-05',
        'Single-blind',
        'Hybrid'
    ),
    (
        19,
        'Asia-Pacific Symposium on Cloud Computing',
        'APSCC',
        '2024-09-10',
        'Seoul, South Korea',
        12,
        0.19,
        '2024-04-01',
        'Double-blind',
        'Virtual'
    ),
    (
        20,
        'International Conference on Intelligent Systems',
        'ICIS',
        '2024-10-05',
        'Tokyo, Japan',
        14,
        0.21,
        '2024-05-15',
        'Single-blind',
        'Physical'
    ),
    (
        21,
        'Asian Symposium on Blockchain Technology',
        'ASBT',
        '2024-11-20',
        'Beijing, China',
        16,
        0.23,
        '2024-06-05',
        'Double-blind',
        'Hybrid'
    ),
    (
        22,
        'Asia-Pacific Conference on Multimedia',
        'APCM',
        '2024-12-15',
        'Kuala Lumpur, Malaysia',
        18,
        0.25,
        '2024-07-10',
        'Single-blind',
        'Virtual'
    ),
    (
        23,
        'International Conference on E-Learning',
        'ICEL',
        '2024-01-12',
        'Jakarta, Indonesia',
        20,
        0.28,
        '2023-09-01',
        'Double-blind',
        'Physical'
    ),
    (
        24,
        'Asian Conference on Information Retrieval',
        'ACIR',
        '2024-02-18',
        'Hanoi, Vietnam',
        25,
        0.24,
        '2023-10-10',
        'Single-blind',
        'Hybrid'
    ),
    (
        25,
        'Asia-Pacific Symposium on Mobile Computing',
        'APS-MC',
        '2024-03-22',
        'Hong Kong',
        30,
        0.2,
        '2023-11-05',
        'Double-blind',
        'Virtual'
    ),
    (
        26,
        'International Conference on Computer Graphics',
        'ICCG',
        '2024-04-18',
        'Manila, Philippines',
        35,
        0.22,
        '2023-11-25',
        'Single-blind',
        'Physical'
    ),
    (
        27,
        'Asian Symposium on Data Mining',
        'ASDM',
        '2024-05-12',
        'Taipei, Taiwan',
        40,
        0.27,
        '2023-12-05',
        'Double-blind',
        'Hybrid'
    ),
    (
        28,
        'Asia-Pacific Conference on Wireless Networks',
        'APCWN',
        '2024-06-15',
        'Shanghai, China',
        45,
        0.19,
        '2024-01-20',
        'Single-blind',
        'Virtual'
    ),
    (
        29,
        'International Symposium on Virtual Reality',
        'ISVR',
        '2024-07-22',
        'Ho Chi Minh City, Vietnam',
        50,
        0.23,
        '2024-02-15',
        'Double-blind',
        'Physical'
    ),
    (
        30,
        'Conference on Advanced Computing',
        'CAC Asia',
        '2024-08-28',
        'Chennai, India',
        55,
        0.26,
        '2024-03-10',
        'Single-blind',
        'Hybrid'
    ),
    (
        31,
        'Asian Conference on Image Processing',
        'ACIP',
        '2024-09-18',
        'Osaka, Japan',
        60,
        0.21,
        '2024-04-01',
        'Double-blind',
        'Virtual'
    ),
    (
        32,
        'Asia-Pacific Symposium on Artificial Life',
        'APSAL',
        '2024-10-12',
        'Bangkok, Thailand',
        65,
        0.3,
        '2024-05-05',
        'Single-blind',
        'Physical'
    ),
    (
        33,
        'International Conference on Information Security',
        'ICIS Asia',
        '2024-11-08',
        'Singapore',
        70,
        0.24,
        '2024-06-01',
        'Double-blind',
        'Hybrid'
    ),
    (
        34,
        'Asian Symposium on Computational Biology',
        'ASCB',
        '2024-12-02',
        'Seoul, South Korea',
        75,
        0.28,
        '2024-07-05',
        'Single-blind',
        'Virtual'
    ),
    (
        35,
        'Asia-Pacific Conference on Cloud Security',
        'APCCS',
        '2024-01-25',
        'Tokyo, Japan',
        80,
        0.17,
        '2023-09-20',
        'Double-blind',
        'Physical'
    ),
    (
        36,
        'International Symposium on Intelligent Robotics',
        'ISIR',
        '2024-02-15',
        'Beijing, China',
        85,
        0.2,
        '2023-10-15',
        'Single-blind',
        'Hybrid'
    ),
    (
        37,
        'Asian Conference on Cognitive Computing',
        'ACCC',
        '2024-03-28',
        'Kuala Lumpur, Malaysia',
        90,
        0.22,
        '2023-11-10',
        'Double-blind',
        'Virtual'
    ),
    (
        38,
        'Asia-Pacific Symposium on Virtual Environments',
        'APSVE',
        '2024-04-22',
        'Jakarta, Indonesia',
        95,
        0.27,
        '2023-11-30',
        'Single-blind',
        'Physical'
    ),
    (
        39,
        'International Conference on Data Privacy',
        'ICDP',
        '2024-05-18',
        'Hanoi, Vietnam',
        100,
        0.26,
        '2023-12-20',
        'Double-blind',
        'Hybrid'
    ),
    (
        40,
        'Asian Symposium on Semantic Web',
        'ASSW',
        '2024-06-10',
        'Hong Kong',
        10,
        0.23,
        '2024-01-05',
        'Single-blind',
        'Virtual'
    ),
    (
        41,
        'Asia-Pacific Conference on Knowledge Discovery',
        'APCKD',
        '2024-07-05',
        'Manila, Philippines',
        12,
        0.25,
        '2024-02-01',
        'Double-blind',
        'Physical'
    ),
    (
        42,
        'International Symposium on Wireless Sensor Networks',
        'ISWSN',
        '2024-08-20',
        'Taipei, Taiwan',
        14,
        0.28,
        '2024-03-15',
        'Single-blind',
        'Hybrid'
    ),
    (
        43,
        'Asian Conference on Bioinformatics',
        'ACB',
        '2024-09-12',
        'Shanghai, China',
        16,
        0.24,
        '2024-04-10',
        'Double-blind',
        'Virtual'
    ),
    (
        44,
        'Asia-Pacific Symposium on Neural Networks',
        'APSNN',
        '2024-10-08',
        'Ho Chi Minh City, Vietnam',
        18,
        0.19,
        '2024-05-01',
        'Single-blind',
        'Physical'
    ),
    (
        45,
        'International Conference on Computer-Aided Design',
        'ICCAD Asia',
        '2024-11-22',
        'Chennai, India',
        20,
        0.21,
        '2024-06-15',
        'Double-blind',
        'Hybrid'
    ),
    (
        46,
        'Asian Symposium on Distributed Computing',
        'ASDC',
        '2024-12-10',
        'Osaka, Japan',
        25,
        0.23,
        '2024-07-01',
        'Single-blind',
        'Virtual'
    ),
    (
        47,
        'Asia-Pacific Conference on Computer Vision',
        'APCCV',
        '2024-01-08',
        'Bangkok, Thailand',
        30,
        0.27,
        '2023-09-05',
        'Double-blind',
        'Physical'
    ),
    (
        48,
        'International Symposium on Software Testing',
        'ISST',
        '2024-02-10',
        'Singapore',
        35,
        0.19,
        '2023-10-01',
        'Single-blind',
        'Hybrid'
    ),
    (
        49,
        'Asian Conference on Cyber-Physical Systems',
        'ACPS',
        '2024-03-15',
        'Seoul, South Korea',
        40,
        0.22,
        '2023-11-01',
        'Double-blind',
        'Virtual'
    ),
    (
        50,
        'Asia-Pacific Symposium on Information Retrieval',
        'APSIR',
        '2024-04-12',
        'Tokyo, Japan',
        45,
        0.26,
        '2023-11-20',
        'Single-blind',
        'Physical'
    );

-- This is done!