-- Inserting data into Institution
INSERT INTO
    Institution (
        InstitutionID,
        Name,
        Type,
        Address,
        CountryID,
        Ranking,
        ResearchBudget,
        DepartmentCount,
        FoundedYear,
        Website
    )
VALUES
    (
        1,
        'Tokyo University',
        'university',
        '7-3-1 Hongo, Bunkyo-ku, Tokyo, Japan',
        '1',
        '5',
        '50000000',
        '30',
        '1877',
        'http://www.u-tokyo.ac.jp'
    ),
    (
        2,
        'National University of Singapore',
        'university',
        '21 Lower Kent Ridge Rd, Singapore',
        '2',
        '11',
        '60000000',
        '25',
        '1905',
        'http://www.nus.edu.sg'
    ),
    (
        3,
        'Tsinghua University',
        'university',
        '30 Shuangqing Rd, Haidian District, Beijing, China',
        '3',
        '17',
        '70000000',
        '40',
        '1911',
        'http://www.tsinghua.edu.cn'
    ),
    (
        4,
        'KAIST',
        'university',
        '291 Daehak-ro, Yuseong-gu, Daejeon, South Korea',
        '4',
        '39',
        '55000000',
        '20',
        '1971',
        'http://www.kaist.ac.kr'
    ),
    (
        5,
        'University of Hong Kong',
        'university',
        'Pok Fu Lam, Hong Kong',
        '5',
        '22',
        '62000000',
        '35',
        '1911',
        'http://www.hku.hk'
    ),
    (
        6,
        'Indian Institute of Science',
        'research_institute',
        'CV Raman Rd, Bengaluru, Karnataka, India',
        '6',
        '29',
        '48000000',
        '20',
        '1909',
        'http://www.iisc.ac.in'
    ),
    (
        7,
        'Peking University',
        'university',
        '5 Yiheyuan Rd, Haidian District, Beijing, China',
        '3',
        '23',
        '75000000',
        '45',
        '1898',
        'http://www.pku.edu.cn'
    ),
    (
        8,
        'Nanyang Technological University',
        'university',
        '50 Nanyang Ave, Singapore',
        '2',
        '13',
        '65000000',
        '28',
        '1981',
        'http://www.ntu.edu.sg'
    ),
    (
        9,
        'University of Tokyo',
        'university',
        '7-3-1 Hongo, Bunkyo-ku, Tokyo, Japan',
        '1',
        '9',
        '80000000',
        '50',
        '1877',
        'http://www.u-tokyo.ac.jp'
    ),
    (
        10,
        'Seoul National University',
        'university',
        '1 Gwanak-ro, Gwanak-gu, Seoul, South Korea',
        '4',
        '37',
        '59000000',
        '38',
        '1946',
        'http://www.snu.ac.kr'
    ),
    (
        11,
        'University of Malaya',
        'university',
        'Kuala Lumpur, Malaysia',
        '7',
        '59',
        '30000000',
        '25',
        '1949',
        'http://www.um.edu.my'
    ),
    (
        12,
        'Zhejiang University',
        'university',
        '866 Yuhangtang Rd, Hangzhou, Zhejiang, China',
        '3',
        '53',
        '68000000',
        '42',
        '1897',
        'http://www.zju.edu.cn'
    ),
    (
        13,
        'Fudan University',
        'university',
        '220 Handan Rd, Yangpu District, Shanghai, China',
        '3',
        '34',
        '72000000',
        '30',
        '1905',
        'http://www.fudan.edu.cn'
    ),
    (
        14,
        'University of the Philippines',
        'university',
        'Diliman, Quezon City, Philippines',
        '8',
        '95',
        '25000000',
        '22',
        '1908',
        'http://www.up.edu.ph'
    ),
    (
        15,
        'Kyoto University',
        'university',
        'Yoshida-honmachi, Sakyo-ku, Kyoto, Japan',
        '1',
        '36',
        '56000000',
        '32',
        '1897',
        'http://www.kyoto-u.ac.jp'
    ),
    (
        16,
        'Osaka University',
        'university',
        '1-1 Yamadaoka, Suita, Osaka, Japan',
        '1',
        '72',
        '47000000',
        '28',
        '1931',
        'http://www.osaka-u.ac.jp'
    ),
    (
        17,
        'Shanghai Jiao Tong University',
        'university',
        '800 Dongchuan Rd, Minhang District, Shanghai, China',
        '3',
        '47',
        '73000000',
        '35',
        '1896',
        'http://www.sjtu.edu.cn'
    ),
    (
        18,
        'Indian Institute of Technology Bombay',
        'university',
        'Powai, Mumbai, Maharashtra, India',
        '6',
        '44',
        '52000000',
        '18',
        '1958',
        'http://www.iitb.ac.in'
    ),
    (
        19,
        'National Taiwan University',
        'university',
        'No. 1, Sec. 4, Roosevelt Rd, Da''an District, Taipei City, Taiwan',
        '9',
        '69',
        '40000000',
        '33',
        '1928',
        'http://www.ntu.edu.tw'
    ),
    (
        20,
        'University of Indonesia',
        'university',
        'Depok, West Java, Indonesia',
        '10',
        '77',
        '29000000',
        '29',
        '1849',
        'http://www.ui.ac.id'
    ),
    (
        21,
        'King Abdulaziz University',
        'university',
        'Jeddah, Saudi Arabia',
        '11',
        '201',
        '45000000',
        '40',
        '1967',
        'http://www.kau.edu.sa'
    ),
    (
        22,
        'Indian Institute of Technology Delhi',
        'university',
        'Hauz Khas, New Delhi, Delhi, India',
        '6',
        '185',
        '50000000',
        '16',
        '1961',
        'http://www.iitd.ac.in'
    ),
    (
        23,
        'University of Science and Technology of China',
        'university',
        '96 Jinzhai Rd, Baohe District, Hefei, Anhui, China',
        '3',
        '93',
        '69000000',
        '27',
        '1958',
        'http://www.ustc.edu.cn'
    ),
    (
        24,
        'Korea University',
        'university',
        '145 Anam-ro, Seongbuk-gu, Seoul, South Korea',
        '4',
        '83',
        '51000000',
        '37',
        '1905',
        'http://www.korea.ac.kr'
    ),
    (
        25,
        'Nagoya University',
        'university',
        'Furo-cho, Chikusa-ku, Nagoya, Aichi, Japan',
        '1',
        '111',
        '38000000',
        '21',
        '1871',
        'http://www.nagoya-u.ac.jp'
    ),
    (
        26,
        'Chulalongkorn University',
        'university',
        '254 Phayathai Rd, Pathum Wan District, Bangkok, Thailand',
        '12',
        '151',
        '32000000',
        '26',
        '1917',
        'http://www.chula.ac.th'
    ),
    (
        27,
        'Hong Kong University of Science and Technology',
        'university',
        'Clear Water Bay, Kowloon, Hong Kong',
        '5',
        '38',
        '64000000',
        '24',
        '1991',
        'http://www.ust.hk'
    ),
    (
        28,
        'Yonsei University',
        'university',
        '50 Yonsei-ro, Seodaemun-gu, Seoul, South Korea',
        '4',
        '85',
        '53000000',
        '34',
        '1885',
        'http://www.yonsei.ac.kr'
    ),
    (
        29,
        'Indian Institute of Technology Madras',
        'university',
        'Sardar Patel Rd, Chennai, Tamil Nadu, India',
        '6',
        '184',
        '47000000',
        '19',
        '1959',
        'http://www.iitm.ac.in'
    ),
    (
        30,
        'City University of Hong Kong',
        'university',
        'Tat Chee Ave, Kowloon Tong, Hong Kong',
        '5',
        '48',
        '61000000',
        '23',
        '1984',
        'http://www.cityu.edu.hk'
    ),
    (
        31,
        'Nankai University',
        'university',
        '94 Weijin Rd, Nankai District, Tianjin, China',
        '3',
        '101',
        '54000000',
        '31',
        '1919',
        'http://www.nankai.edu.cn'
    ),
    (
        32,
        'National Cheng Kung University',
        'university',
        'No. 1, University Rd, East District, Tainan City, Taiwan',
        '9',
        '171',
        '35000000',
        '28',
        '1931',
        'http://www.ncku.edu.tw'
    ),
    (
        33,
        'Hokkaido University',
        'university',
        'Kita 8, Nishi 5, Kita-ku, Sapporo, Hokkaido, Japan',
        '1',
        '131',
        '41000000',
        '29',
        '1876',
        'http://www.hokudai.ac.jp'
    ),
    (
        34,
        'Kyushu University',
        'university',
        '744 Motooka, Nishi-ku, Fukuoka, Japan',
        '1',
        '141',
        '39000000',
        '22',
        '1911',
        'http://www.kyushu-u.ac.jp'
    ),
    (
        35,
        'Indian Institute of Technology Kanpur',
        'university',
        'Kalyanpur, Kanpur, Uttar Pradesh, India',
        '6',
        '211',
        '46000000',
        '17',
        '1959',
        'http://www.iitk.ac.in'
    ),
    (
        36,
        'Sun Yat-sen University',
        'university',
        '135 Xingang W Rd, Haizhu District, Guangzhou, Guangdong, China',
        '3',
        '113',
        '67000000',
        '36',
        '1924',
        'http://www.sysu.edu.cn'
    ),
    (
        37,
        'American University of Beirut',
        'university',
        'Bliss St, Beirut, Lebanon',
        '13',
        '231',
        '34000000',
        '27',
        '1866',
        'http://www.aub.edu.lb'
    ),
    (
        38,
        'National Tsing Hua University',
        'university',
        'No. 101, Section 2, Kuang-Fu Rd, East District, Hsinchu City, Taiwan',
        '9',
        '151',
        '37000000',
        '25',
        '1911',
        'http://www.nthu.edu.tw'
    ),
    (
        39,
        'Indian Institute of Technology Kharagpur',
        'university',
        'Kharagpur, West Bengal, India',
        '6',
        '281',
        '43000000',
        '20',
        '1951',
        'http://www.iitkgp.ac.in'
    ),
    (
        40,
        'Shanghai University',
        'university',
        '99 Shangda Rd, Baoshan District, Shanghai, China',
        '3',
        '301',
        '55000000',
        '32',
        '1922',
        'http://www.shu.edu.cn'
    ),
    (
        41,
        'University of Tehran',
        'university',
        'Tehran, Iran',
        '14',
        '251',
        '28000000',
        '30',
        '1934',
        'http://www.ut.ac.ir'
    ),
    (
        42,
        'King Fahd University of Petroleum & Minerals',
        'university',
        'Dhahran, Saudi Arabia',
        '11',
        '221',
        '42000000',
        '18',
        '1963',
        'http://www.kfupm.edu.sa'
    ),
    (
        43,
        'National Chiao Tung University',
        'university',
        'No. 1001, University Rd, East District, Hsinchu City, Taiwan',
        '9',
        '161',
        '36000000',
        '24',
        '1896',
        'http://www.nctu.edu.tw'
    ),
    (
        44,
        'University of Baghdad',
        'university',
        'Baghdad, Iraq',
        '15',
        '401',
        '26000000',
        '31',
        '1957',
        'http://www.uobaghdad.edu.iq'
    ),
    (
        45,
        'University of Karachi',
        'university',
        'Karachi, Pakistan',
        '16',
        '451',
        '24000000',
        '33',
        '1951',
        'http://www.uok.edu.pk'
    ),
    (
        46,
        'University of Dhaka',
        'university',
        'Dhaka, Bangladesh',
        '17',
        '301',
        '27000000',
        '34',
        '1921',
        'http://www.du.ac.bd'
    ),
    (
        47,
        'King Saud University',
        'university',
        'Riyadh, Saudi Arabia',
        '11',
        '251',
        '43000000',
        '40',
        '1957',
        'http://www.ksu.edu.sa'
    ),
    (
        48,
        'University of Colombo',
        'university',
        'Colombo, Sri Lanka',
        '18',
        '401',
        '22000000',
        '22',
        '1921',
        'http://www.cmb.ac.lk'
    ),
    (
        49,
        'University of Jordan',
        'university',
        'Amman, Jordan',
        '19',
        '351',
        '29000000',
        '28',
        '1962',
        'http://www.ju.edu.jo'
    ),
    (
        50,
        'University of Haifa',
        'university',
        'Haifa, Israel',
        '20',
        '451',
        '31000000',
        '26',
        '1963',
        'http://www.haifa.ac.il'
    );