-- Inserting data into Journal
INSERT INTO
    Journal (
        JournalID,
        `Name`,
        ISSN,
        ImpactFactor,
        Publisher,
        Frequency,
        Scope,
        ReviewTime,
        AcceptanceRate,
        OpenAccessStatus
    )
VALUES
    (
        1,
        'Asian Journal of Science',
        '1234-5678',
        5.6,
        'Asian Science Publishers',
        'Monthly',
        'Science and Technology',
        90,
        0.25,
        'OPEN_ACCESS'
    ),
    (
        2,
        'Journal of Asian Studies',
        '2345-6789',
        2.3,
        'Asia Research Group',
        'Quarterly',
        'Asian Studies',
        120,
        0.3,
        'SUBSCRIPTION_BASED'
    ),
    (
        3,
        'Asian Economic Review',
        '3456-7890',
        4.7,
        'Economic Research Institute',
        'Biannual',
        'Economics',
        60,
        0.2,
        'HYBRID'
    ),
    (
        4,
        'Journal of Asian Medicine',
        '4567-8901',
        3.1,
        'Asian Medical Association',
        'Monthly',
        'Medicine',
        75,
        0.15,
        'OPEN_ACCESS'
    ),
    (
        5,
        'Asian Journal of Education',
        '5678-9012',
        1.8,
        'Educational Publishers Asia',
        'Quarterly',
        'Education',
        100,
        0.35,
        'SUBSCRIPTION_BASED'
    ),
    (
        6,
        'Journal of Asian Politics',
        '6789-0123',
        3.9,
        'Political Science Network',
        'Biannual',
        'Politics',
        110,
        0.22,
        'HYBRID'
    ),
    (
        7,
        'Asian Journal of Environmental Science',
        '7890-1234',
        6.5,
        'Environment Asia',
        'Monthly',
        'Environmental Science',
        85,
        0.18,
        'OPEN_ACCESS'
    ),
    (
        8,
        'Journal of Asian Literature',
        '8901-2345',
        1.2,
        'Literary Asia',
        'Quarterly',
        'Literature',
        140,
        0.32,
        'SUBSCRIPTION_BASED'
    ),
    (
        9,
        'Asian Journal of Sociology',
        '9012-3456',
        2.7,
        'Sociology Research Group',
        'Biannual',
        'Sociology',
        95,
        0.28,
        'HYBRID'
    ),
    (
        10,
        'Journal of Asian Art',
        '0123-4567',
        0.9,
        'Art Asia Publications',
        'Quarterly',
        'Art',
        130,
        0.36,
        'SUBSCRIPTION_BASED'
    ),
    (
        11,
        'Asian Journal of Engineering',
        '1234-5679',
        7.3,
        'Engineering Asia',
        'Monthly',
        'Engineering',
        70,
        0.2,
        'OPEN_ACCESS'
    ),
    (
        12,
        'Journal of Asian History',
        '2345-6780',
        1.5,
        'History Network Asia',
        'Quarterly',
        'History',
        150,
        0.34,
        'SUBSCRIPTION_BASED'
    ),
    (
        13,
        'Asian Journal of Psychology',
        '3456-7891',
        3.4,
        'Psychology Asia',
        'Biannual',
        'Psychology',
        80,
        0.26,
        'HYBRID'
    ),
    (
        14,
        'Journal of Asian Agriculture',
        '4567-8902',
        4.2,
        'Agriculture Research Asia',
        'Monthly',
        'Agriculture',
        90,
        0.24,
        'OPEN_ACCESS'
    ),
    (
        15,
        'Asian Journal of Law',
        '5678-9013',
        2.0,
        'Law Publications Asia',
        'Quarterly',
        'Law',
        125,
        0.31,
        'SUBSCRIPTION_BASED'
    ),
    (
        16,
        'Journal of Asian Linguistics',
        '6789-0124',
        1.9,
        'Linguistics Asia',
        'Biannual',
        'Linguistics',
        135,
        0.3,
        'HYBRID'
    ),
    (
        17,
        'Asian Journal of Computer Science',
        '7890-1235',
        8.1,
        'Computer Science Asia',
        'Monthly',
        'Computer Science',
        60,
        0.19,
        'OPEN_ACCESS'
    ),
    (
        18,
        'Journal of Asian Philosophy',
        '8901-2346',
        1.3,
        'Philosophy Network Asia',
        'Quarterly',
        'Philosophy',
        145,
        0.33,
        'SUBSCRIPTION_BASED'
    ),
    (
        19,
        'Asian Journal of Chemistry',
        '9012-3457',
        5.2,
        'Chemistry Research Asia',
        'Biannual',
        'Chemistry',
        85,
        0.23,
        'HYBRID'
    ),
    (
        20,
        'Journal of Asian Mathematics',
        '0123-4568',
        3.6,
        'Mathematics Asia',
        'Monthly',
        'Mathematics',
        75,
        0.27,
        'OPEN_ACCESS'
    ),
    (
        21,
        'Asian Journal of Biotechnology',
        '1234-5670',
        6.8,
        'Biotech Asia',
        'Quarterly',
        'Biotechnology',
        100,
        0.21,
        'SUBSCRIPTION_BASED'
    ),
    (
        22,
        'Journal of Asian Anthropology',
        '2345-6781',
        2.5,
        'Anthropology Asia',
        'Biannual',
        'Anthropology',
        115,
        0.29,
        'HYBRID'
    ),
    (
        23,
        'Asian Journal of Physics',
        '3456-7892',
        7.7,
        'Physics Research Asia',
        'Monthly',
        'Physics',
        65,
        0.17,
        'OPEN_ACCESS'
    ),
    (
        24,
        'Journal of Asian Geography',
        '4567-8903',
        1.7,
        'Geography Network Asia',
        'Quarterly',
        'Geography',
        140,
        0.35,
        'SUBSCRIPTION_BASED'
    ),
    (
        25,
        'Asian Journal of Nutrition',
        '5678-9014',
        3.3,
        'Nutrition Research Asia',
        'Biannual',
        'Nutrition',
        90,
        0.26,
        'HYBRID'
    ),
    (
        26,
        'Journal of Asian Culture',
        '6789-0125',
        1.1,
        'Culture Asia Publications',
        'Quarterly',
        'Culture',
        155,
        0.37,
        'SUBSCRIPTION_BASED'
    ),
    (
        27,
        'Asian Journal of Materials Science',
        '7890-1236',
        6.0,
        'Materials Science Asia',
        'Monthly',
        'Materials Science',
        80,
        0.22,
        'OPEN_ACCESS'
    ),
    (
        28,
        'Journal of Asian Ethics',
        '8901-2347',
        1.4,
        'Ethics Network Asia',
        'Quarterly',
        'Ethics',
        150,
        0.34,
        'SUBSCRIPTION_BASED'
    ),
    (
        29,
        'Asian Journal of Geology',
        '9012-3458',
        4.9,
        'Geology Research Asia',
        'Biannual',
        'Geology',
        95,
        0.25,
        'HYBRID'
    ),
    (
        30,
        'Journal of Asian Music',
        '0123-4569',
        0.8,
        'Music Asia Publications',
        'Quarterly',
        'Music',
        160,
        0.38,
        'SUBSCRIPTION_BASED'
    ),
    (
        31,
        'Asian Journal of Robotics',
        '1234-5671',
        8.5,
        'Robotics Asia',
        'Monthly',
        'Robotics',
        70,
        0.18,
        'OPEN_ACCESS'
    ),
    (
        32,
        'Journal of Asian Theology',
        '2345-6782',
        1.6,
        'Theology Network Asia',
        'Quarterly',
        'Theology',
        145,
        0.33,
        'SUBSCRIPTION_BASED'
    ),
    (
        33,
        'Asian Journal of Zoology',
        '3456-7893',
        4.5,
        'Zoology Research Asia',
        'Biannual',
        'Zoology',
        85,
        0.24,
        'HYBRID'
    ),
    (
        34,
        'Journal of Asian Fashion',
        '4567-8904',
        0.7,
        'Fashion Asia Publications',
        'Quarterly',
        'Fashion',
        165,
        0.39,
        'SUBSCRIPTION_BASED'
    ),
    (
        35,
        'Asian Journal of Architecture',
        '5678-9015',
        2.8,
        'Architecture Asia',
        'Monthly',
        'Architecture',
        100,
        0.3,
        'OPEN_ACCESS'
    ),
    (
        36,
        'Journal of Asian Public Health',
        '6789-0126',
        3.8,
        'Public Health Network Asia',
        'Quarterly',
        'Public Health',
        110,
        0.28,
        'SUBSCRIPTION_BASED'
    ),
    (
        37,
        'Asian Journal of Astronomy',
        '7890-1237',
        7.0,
        'Astronomy Research Asia',
        'Biannual',
        'Astronomy',
        75,
        0.21,
        'HYBRID'
    ),
    (
        38,
        'Journal of Asian Dance',
        '8901-2348',
        0.6,
        'Dance Asia Publications',
        'Quarterly',
        'Dance',
        170,
        0.4,
        'SUBSCRIPTION_BASED'
    ),
    (
        39,
        'Asian Journal of Marine Biology',
        '9012-3459',
        5.4,
        'Marine Biology Asia',
        'Monthly',
        'Marine Biology',
        90,
        0.23,
        'OPEN_ACCESS'
    ),
    (
        40,
        'Journal of Asian Film Studies',
        '0123-4570',
        1.0,
        'Film Studies Asia',
        'Quarterly',
        'Film Studies',
        155,
        0.36,
        'SUBSCRIPTION_BASED'
    ),
    (
        41,
        'Asian Journal of Veterinary Science',
        '1234-5672',
        3.7,
        'Veterinary Science Asia',
        'Biannual',
        'Veterinary Science',
        95,
        0.27,
        'HYBRID'
    ),
    (
        42,
        'Journal of Asian Religious Studies',
        '2345-6783',
        1.2,
        'Religious Studies Network Asia',
        'Quarterly',
        'Religious Studies',
        160,
        0.35,
        'SUBSCRIPTION_BASED'
    ),
    (
        43,
        'Asian Journal of Nanotechnology',
        '3456-7894',
        9.2,
        'Nanotechnology Asia',
        'Monthly',
        'Nanotechnology',
        65,
        0.16,
        'OPEN_ACCESS'
    ),
    (
        44,
        'Journal of Asian Performing Arts',
        '4567-8905',
        0.5,
        'Performing Arts Asia Publications',
        'Quarterly',
        'Performing Arts',
        175,
        0.39,
        'SUBSCRIPTION_BASED'
    ),
    (
        45,
        'Asian Journal of Pharmacology',
        '5678-9016',
        4.4,
        'Pharmacology Research Asia',
        'Biannual',
        'Pharmacology',
        85,
        0.25,
        'HYBRID'
    ),
    (
        46,
        'Journal of Asian Architecture',
        '6789-0127',
        2.6,
        'Architecture Network Asia',
        'Quarterly',
        'Architecture',
        120,
        0.31,
        'SUBSCRIPTION_BASED'
    ),
    (
        47,
        'Asian Journal of Genetics',
        '7890-1238',
        6.9,
        'Genetics Asia',
        'Monthly',
        'Genetics',
        70,
        0.2,
        'OPEN_ACCESS'
    ),
    (
        48,
        'Journal of Asian Theatre',
        '8901-2349',
        0.9,
        'Theatre Asia Publications',
        'Quarterly',
        'Theatre',
        165,
        0.38,
        'SUBSCRIPTION_BASED'
    ),
    (
        49,
        'Asian Journal of Ecology',
        '9012-3460',
        5.1,
        'Ecology Research Asia',
        'Biannual',
        'Ecology',
        100,
        0.24,
        'HYBRID'
    ),
    (
        50,
        'Journal of Asian Culinary Studies',
        '0123-4571',
        0.6,
        'Culinary Studies Asia',
        'Quarterly',
        'Culinary Studies',
        170,
        0.39,
        'SUBSCRIPTION_BASED'
    );

-- this is done!