-- Inserting data into Publication
INSERT INTO
    Publication (
        PublicationID,
        ConferenceID,
        JournalID,
        Field,
        TopicID,
        Title,
        Abstract,
        PublicationDate,
        `Version`,
        `Status`,
        `PageCount`,
        `Language`,
        LicenseType,
        FullTextURL,
        CitationCount
    )
VALUES
    (
        1,
        1,
        1,
        'Computer Science',
        1,
        'Advancements in Quantum Computing',
        'This paper discusses recent advancements in quantum computing and its applications.',
        '2023-01-15',
        '1.0',
        'PUBLISHED',
        '30',
        'English',
        'CC BY 4.0',
        'https://example.com/publication1',
        150
    ),
    (
        2,
        2,
        2,
        'Biotechnology',
        2,
        'CRISPR-Cas9: A Revolutionary Tool in Genetic Engineering',
        'An exploration of CRISPR-Cas9 technology and its impact on genetic engineering.',
        '2023-02-20',
        '1.1',
        'ACCEPTED',
        '25',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication2',
        200
    ),
    (
        3,
        3,
        3,
        'Physics',
        3,
        'Exploring the Higgs Boson',
        'An in-depth analysis of the Higgs boson and its significance in particle physics.',
        '2023-03-10',
        '2.0',
        'PUBLISHED',
        '40',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication3',
        300
    ),
    (
        4,
        4,
        4,
        'Artificial Intelligence',
        4,
        'Machine Learning Algorithms: A Comprehensive Overview',
        'A comprehensive overview of various machine learning algorithms and their applications.',
        '2023-04-05',
        '1.2',
        'SUBMITTED',
        '35',
        'English',
        'CC BY 4.0',
        'https://example.com/publication4',
        250
    ),
    (
        5,
        5,
        5,
        'Medicine',
        5,
        'The Role of AI in Modern Healthcare',
        'This study explores the integration of AI technologies in modern healthcare systems.',
        '2023-05-12',
        '1.0',
        'UNDER_REVIEW',
        '28',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication5',
        180
    ),
    (
        6,
        6,
        6,
        'Environmental Science',
        6,
        'Climate Change and Its Impact on Biodiversity',
        'An analysis of how climate change is affecting biodiversity across the globe.',
        '2023-06-18',
        '1.3',
        'PUBLISHED',
        '32',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication6',
        220
    ),
    (
        7,
        7,
        7,
        'Robotics',
        7,
        'Autonomous Robots: Challenges and Opportunities',
        'This paper examines the challenges and opportunities in the field of autonomous robotics.',
        '2023-07-22',
        '1.0',
        'ACCEPTED',
        '29',
        'English',
        'CC BY 4.0',
        'https://example.com/publication7',
        170
    ),
    (
        8,
        8,
        8,
        'Astronomy',
        8,
        'The Mysteries of Dark Matter',
        'An exploration of dark matter and its role in the universe.',
        '2023-08-30',
        '1.1',
        'DRAFT',
        '34',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication8',
        140
    ),
    (
        9,
        9,
        9,
        'Chemistry',
        9,
        'Nanotechnology in Chemical Engineering',
        'A detailed study on the applications of nanotechnology in chemical engineering.',
        '2023-09-15',
        '2.0',
        'PUBLISHED',
        '45',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication9',
        310
    ),
    (
        10,
        10,
        10,
        'Economics',
        10,
        'The Impact of Globalization on Emerging Markets',
        'An analysis of how globalization is affecting emerging markets around the world.',
        '2023-10-01',
        '1.2',
        'RETRACTED',
        '38',
        'English',
        'CC BY 4.0',
        'https://example.com/publication10',
        90
    ),
    (
        11,
        11,
        11,
        'Psychology',
        11,
        'Cognitive Behavioral Therapy: Techniques and Applications',
        'An overview of cognitive behavioral therapy techniques and their applications in clinical settings.',
        '2023-01-25',
        '1.0',
        'PUBLISHED',
        '27',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication11',
        210
    ),
    (
        12,
        12,
        12,
        'Sociology',
        12,
        'Social Media and Its Impact on Society',
        'A study on the effects of social media on societal behavior and communication.',
        '2023-02-14',
        '1.1',
        'ACCEPTED',
        '31',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication12',
        240
    ),
    (
        13,
        13,
        13,
        'Education',
        13,
        'E-Learning: Transforming Education in the Digital Age',
        'An exploration of how e-learning is transforming education in the digital age.',
        '2023-03-22',
        '2.0',
        'PUBLISHED',
        '36',
        'English',
        'CC BY 4.0',
        'https://example.com/publication13',
        260
    ),
    (
        14,
        14,
        14,
        'History',
        14,
        'The Renaissance: A Period of Cultural Rebirth',
        'A historical analysis of the Renaissance period and its impact on art and culture.',
        '2023-04-18',
        '1.2',
        'SUBMITTED',
        '33',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication14',
        130
    ),
    (
        15,
        15,
        15,
        'Political Science',
        15,
        'Democracy in the 21st Century: Challenges and Prospects',
        'An examination of the challenges and prospects for democracy in the 21st century.',
        '2023-05-25',
        '1.0',
        'UNDER_REVIEW',
        '29',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication15',
        160
    ),
    (
        16,
        16,
        16,
        'Philosophy',
        16,
        'Existentialism: Understanding the Human Condition',
        'A philosophical exploration of existentialism and its insights into the human condition.',
        '2023-06-30',
        '1.3',
        'PUBLISHED',
        '35',
        'English',
        'CC BY 4.0',
        'https://example.com/publication16',
        190
    ),
    (
        17,
        '17',
        '17',
        'Linguistics',
        17,
        'The Evolution of Language: From Ancient to Modern Times',
        'A study on the evolution of language from ancient to modern times.',
        '2023-07-10',
        '1.0',
        'ACCEPTED',
        '28',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication17',
        110
    ),
    (
        18,
        18,
        18,
        'Anthropology',
        18,
        'Cultural Anthropology: Understanding Human Societies',
        'An exploration of cultural anthropology and its role in understanding human societies.',
        '2023-08-05',
        '1.1',
        'DRAFT',
        '32',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication18',
        100
    ),
    (
        19,
        19,
        19,
        'Geography',
        19,
        'Geospatial Technologies: Mapping the World',
        'A study on the applications of geospatial technologies in mapping and understanding the world.',
        '2023-09-18',
        '2.0',
        'PUBLISHED',
        '37',
        'English',
        'CC BY 4.0',
        'https://example.com/publication19',
        230
    ),
    (
        20,
        20,
        20,
        'Law',
        20,
        'International Law and Human Rights',
        'An examination of international law and its role in protecting human rights.',
        '2023-10-12',
        '1.2',
        'RETRACTED',
        '39',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication20',
        80
    ),
    (
        21,
        21,
        21,
        'Engineering',
        21,
        'Renewable Energy Technologies: Innovations and Challenges',
        'An exploration of innovations and challenges in renewable energy technologies.',
        '2023-01-05',
        '1.0',
        'PUBLISHED',
        '34',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication21',
        270
    ),
    (
        22,
        22,
        22,
        'Mathematics',
        22,
        'Topology: An Introduction to Geometric Properties',
        'An introduction to topology and its significance in understanding geometric properties.',
        '2023-02-28',
        '1.1',
        'ACCEPTED',
        '30',
        'English',
        'CC BY 4.0',
        'https://example.com/publication22',
        150
    ),
    (
        23,
        23,
        23,
        'Statistics',
        23,
        'Bayesian Statistics: Theory and Applications',
        'A comprehensive study on Bayesian statistics and its applications in various fields.',
        '2023-03-15',
        '2.0',
        'PUBLISHED',
        '41',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication23',
        190
    ),
    (
        24,
        24,
        24,
        'Architecture',
        24,
        'Sustainable Architecture: Designing for the Future',
        'An exploration of sustainable architecture and its role in designing for the future.',
        '2023-04-10',
        '1.2',
        'SUBMITTED',
        '36',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication24',
        140
    ),
    (
        25,
        25,
        25,
        'Music',
        25,
        'The Evolution of Music: From Classical to Contemporary',
        'A study on the evolution of music from classical to contemporary times.',
        '2023-05-22',
        '1.0',
        'UNDER_REVIEW',
        '29',
        'English',
        'CC BY 4.0',
        'https://example.com/publication25',
        120
    ),
    (
        26,
        26,
        26,
        'Art',
        26,
        'Contemporary Art: Trends and Influences',
        'An analysis of contemporary art trends and the influences shaping them.',
        '2023-06-14',
        '1.3',
        'PUBLISHED',
        '31',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication26',
        180
    ),
    (
        27,
        27,
        27,
        'Theater',
        27,
        'The Role of Theater in Society: Past and Present',
        'An exploration of the role of theater in society throughout history.',
        '2023-07-08',
        '1.0',
        'ACCEPTED',
        '28',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication27',
        90
    ),
    (
        28,
        28,
        28,
        'Film Studies',
        28,
        'Cinematic Techniques: From Silent Films to Digital Media',
        'A study on the evolution of cinematic techniques from silent films to digital media.',
        '2023-08-16',
        '1.1',
        'DRAFT',
        '35',
        'English',
        'CC BY 4.0',
        'https://example.com/publication28',
        130
    ),
    (
        29,
        29,
        29,
        'Dance',
        29,
        'The Art of Dance: Expression and Movement',
        'An exploration of dance as an art form and its role in expression and movement.',
        '2023-09-25',
        '2.0',
        'PUBLISHED',
        '38',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication29',
        160
    ),
    (
        30,
        30,
        30,
        'Literature',
        30,
        'Postmodern Literature: Themes and Techniques',
        'An analysis of themes and techniques in postmodern literature.',
        '2023-10-19',
        '1.2',
        'RETRACTED',
        '40',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication30',
        70
    ),
    (
        31,
        31,
        31,
        'Psychiatry',
        31,
        'Advances in Treatment for Mood Disorders',
        'A review of recent advances in the treatment of mood disorders.',
        '2023-01-12',
        '1.0',
        'PUBLISHED',
        '32',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication31',
        210
    ),
    (
        32,
        32,
        32,
        'Neuroscience',
        32,
        'Neuroplasticity: Understanding the Brain''s Ability to Adapt',
        'An exploration of neuroplasticity and the brain''s ability to adapt to changes.',
        '2023-02-07',
        '1.1',
        'ACCEPTED',
        '30',
        'English',
        'CC BY 4.0',
        'https://example.com/publication32',
        180
    ),
    (
        33,
        33,
        33,
        'Genetics',
        33,
        'The Human Genome Project: Mapping Our DNA',
        'A comprehensive overview of the Human Genome Project and its impact on genetics.',
        '2023-03-28',
        '2.0',
        'PUBLISHED',
        '42',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication33',
        250
    ),
    (
        34,
        34,
        34,
        'Microbiology',
        34,
        'Antibiotic Resistance: A Growing Threat',
        'An analysis of antibiotic resistance and its implications for public health.',
        '2023-04-15',
        '1.2',
        'SUBMITTED',
        '34',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication34',
        160
    ),
    (
        35,
        35,
        35,
        'Geology',
        35,
        'Plate Tectonics: Understanding Earth''s Dynamic Crust',
        'An exploration of plate tectonics and its role in shaping Earth''s crust.',
        '2023-05-20',
        '1.0',
        'UNDER_REVIEW',
        '37',
        'English',
        'CC BY 4.0',
        'https://example.com/publication35',
        140
    ),
    (
        36,
        36,
        36,
        'Oceanography',
        36,
        'The Role of Oceans in Climate Regulation',
        'A study on the role of oceans in regulating Earth''s climate.',
        '2023-06-27',
        '1.3',
        'PUBLISHED',
        '39',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication36',
        220
    ),
    (
        37,
        37,
        37,
        'Meteorology',
        37,
        'Weather Patterns and Climate Change',
        'An analysis of weather patterns and their relationship with climate change.',
        '2023-07-14',
        '1.0',
        'ACCEPTED',
        '33',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication37',
        170
    ),
    (
        38,
        38,
        38,
        'Zoology',
        38,
        'Animal Behavior: Insights into the Natural World',
        'An exploration of animal behavior and its significance in understanding the natural world.',
        '2023-08-09',
        '1.1',
        'DRAFT',
        '31',
        'English',
        'CC BY 4.0',
        'https://example.com/publication38',
        130
    ),
    (
        39,
        39,
        39,
        'Botany',
        39,
        'Plant Physiology: Understanding Growth and Development',
        'A study on plant physiology and the factors influencing growth and development.',
        '2023-09-21',
        '2.0',
        'PUBLISHED',
        '36',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication39',
        190
    ),
    (
        40,
        40,
        40,
        'Ecology',
        40,
        'Ecosystem Dynamics: Interactions and Adaptations',
        'An exploration of ecosystem dynamics and the interactions and adaptations within them.',
        '2023-10-11',
        '1.2',
        'RETRACTED',
        '38',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication40',
        80
    ),
    (
        41,
        41,
        41,
        'Immunology',
        41,
        'Vaccines: Innovations in Disease Prevention',
        'A review of recent innovations in vaccine development and their role in disease prevention.',
        '2023-01-18',
        '1.0',
        'PUBLISHED',
        '32',
        'English',
        'CC BY 4.0',
        'https://example.com/publication41',
        200
    ),
    (
        42,
        42,
        42,
        'Virology',
        42,
        'Understanding Viral Pathogenesis: Mechanisms and Implications',
        'An exploration of viral pathogenesis and its implications for public health.',
        '2023-02-11',
        '1.1',
        'ACCEPTED',
        '30',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication42',
        180
    ),
    (
        43,
        43,
        43,
        'Pharmacology',
        43,
        'Drug Development: From Discovery to Market',
        'An overview of the drug development process from discovery to market.',
        '2023-03-30',
        '2.0',
        'PUBLISHED',
        '40',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication43',
        220
    ),
    (
        44,
        44,
        44,
        'Toxicology',
        44,
        'Environmental Toxins: Impact on Human Health',
        'An analysis of environmental toxins and their impact on human health.',
        '2023-04-25',
        '1.2',
        'SUBMITTED',
        '34',
        'English',
        'CC BY 4.0',
        'https://example.com/publication44',
        160
    ),
    (
        45,
        45,
        45,
        'Nutrition',
        45,
        'Nutritional Science: Exploring Diet and Health',
        'An exploration of nutritional science and its role in promoting health through diet.',
        '2023-05-17',
        '1.0',
        'UNDER_REVIEW',
        '31',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication45',
        130
    ),
    (
        46,
        46,
        46,
        'Dermatology',
        46,
        'Skin Disorders: Diagnosis and Treatment',
        'A review of common skin disorders and the latest advancements in their diagnosis and treatment.',
        '2023-06-22',
        '1.3',
        'PUBLISHED',
        '33',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication46',
        150
    ),
    (
        47,
        47,
        47,
        'Cardiology',
        47,
        'Cardiovascular Diseases: Prevention and Management',
        'An exploration of prevention and management strategies for cardiovascular diseases.',
        '2023-07-19',
        '1.0',
        'ACCEPTED',
        '35',
        'English',
        'CC BY 4.0',
        'https://example.com/publication47',
        160
    ),
    (
        48,
        48,
        48,
        'Oncology',
        48,
        'Cancer Research: Breakthroughs and Challenges',
        'A review of recent breakthroughs and ongoing challenges in cancer research.',
        '2023-08-29',
        '1.1',
        'DRAFT',
        '32',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication48',
        170
    ),
    (
        49,
        49,
        49,
        'Endocrinology',
        49,
        'Hormonal Regulation: Insights into Endocrine Function',
        'An exploration of hormonal regulation and its role in endocrine function.',
        '2023-09-05',
        '2.0',
        'PUBLISHED',
        '39',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication49',
        200
    ),
    (
        50,
        50,
        50,
        'Gastroenterology',
        50,
        'Digestive Health: Advances in Diagnosis and Treatment',
        'A review of advances in the diagnosis and treatment of digestive health disorders.',
        '2023-10-23',
        '1.2',
        'RETRACTED',
        '40',
        'English',
        'CC BY 4.0',
        'https://example.com/publication50',
        90
    ),
    (
        51,
        '51',
        '51',
        'Computer Science',
        'TOPIC_51',
        'Blockchain Technology: Applications and Challenges',
        'An overview of blockchain technology, its applications, and future challenges.',
        '2023-11-02',
        '1.0',
        'PUBLISHED',
        '35',
        'English',
        'CC BY-NC-SA 4.0',
        'https://example.com/publication51',
        95
    ),
    (
        52,
        '52',
        '52',
        'Materials Science',
        'TOPIC_52',
        'Nanomaterials: Synthesis and Functionalization',
        'Discussion of synthesis and functionalization techniques for nanomaterials.',
        '2023-11-10',
        '1.1',
        'SUBMITTED',
        '39',
        'English',
        'CC BY 4.0',
        'https://example.com/publication52',
        120
    ),
    (
        53,
        '53',
        '53',
        'Artificial Intelligence',
        'TOPIC_53',
        'The Rise of AI Ethics: Principles and Policies',
        'An exploration of ethical principles and policies in AI development.',
        '2023-12-01',
        '2.0',
        'DRAFT',
        '30',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication53',
        150
    ),
    (
        54,
        '54',
        '54',
        'Biochemistry',
        'TOPIC_54',
        'Metabolic Pathways: Investigating Cellular Processes',
        'A study on metabolic pathways and their role in cellular processes.',
        '2023-12-15',
        '1.2',
        'ACCEPTED',
        '34',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication54',
        85
    ),
    (
        55,
        '55',
        '55',
        'Earth Science',
        'TOPIC_55',
        'Seismic Activity and Earthquake Prediction',
        'Analyzing seismic activities and advances in earthquake prediction.',
        '2023-12-28',
        '1.0',
        'UNDER_REVIEW',
        '38',
        'English',
        'CC BY-NC-ND 4.0',
        'https://example.com/publication55',
        115
    ),
    (
        56,
        '56',
        '56',
        'Paleontology',
        'TOPIC_56',
        'Dinosaur Extinction: Theories and Evidence',
        'Evaluating theories and evidence surrounding the extinction of dinosaurs.',
        '2024-01-10',
        '1.3',
        'PUBLISHED',
        '29',
        'English',
        'CC BY 4.0',
        'https://example.com/publication56',
        95
    ),
    (
        57,
        '57',
        '57',
        'Astrophysics',
        'TOPIC_57',
        'Gravitational Waves: Exploring the Universe',
        'Insight into gravitational waves and their significance in astrophysics.',
        '2024-01-22',
        '1.0',
        'DRAFT',
        '40',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication57',
        130
    ),
    (
        58,
        '58',
        '58',
        'Biology',
        'TOPIC_58',
        'Genomics and Personalized Medicine',
        'The impact of genomics on the development of personalized medicine.',
        '2024-02-08',
        '1.1',
        'PUBLISHED',
        '36',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication58',
        180
    ),
    (
        59,
        '59',
        '59',
        'Environmental Policy',
        'TOPIC_59',
        'Renewable Energy Policy and Implementation',
        'An analysis of renewable energy policies and their implementation across the globe.',
        '2024-02-20',
        '2.0',
        'RETRACTED',
        '33',
        'English',
        'CC BY 4.0',
        'https://example.com/publication59',
        140
    ),
    (
        60,
        '60',
        '60',
        'History',
        'TOPIC_60',
        'Colonialism: Impact and Legacy',
        'A critical look at the impacts and legacy of colonialism in modern societies.',
        '2024-03-05',
        '1.2',
        'ACCEPTED',
        '37',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication60',
        110
    ),
    (
        61,
        '61',
        '61',
        'Psychology',
        'TOPIC_61',
        'Emotional Intelligence in Leadership',
        'Exploring the role of emotional intelligence in effective leadership.',
        '2024-03-15',
        '1.0',
        'PUBLISHED',
        '29',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication61',
        100
    ),
    (
        62,
        '62',
        '62',
        'Sociology',
        'TOPIC_62',
        'The Sociology of Social Movements',
        'An analysis of social movements and their influence on societal change.',
        '2024-03-28',
        '1.1',
        'UNDER_REVIEW',
        '41',
        'English',
        'CC BY-NC-ND 4.0',
        'https://example.com/publication62',
        170
    ),
    (
        63,
        '63',
        '63',
        'Education',
        'TOPIC_63',
        'Remote Learning in a Post-Pandemic World',
        'Assessment of remote learning technologies and their effectiveness post-pandemic.',
        '2024-04-12',
        '2.0',
        'SUBMITTED',
        '35',
        'English',
        'CC BY 4.0',
        'https://example.com/publication63',
        90
    ),
    (
        64,
        '64',
        '64',
        'Political Science',
        'TOPIC_64',
        'Authoritarianism: Trends and Consequences',
        'An exploration of the rise of authoritarian regimes and implications globally.',
        '2024-04-25',
        '1.2',
        'ACCEPTED',
        '34',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication64',
        100
    ),
    (
        65,
        '65',
        '65',
        'Architecture',
        'TOPIC_65',
        'Biophilic Design: Integrating Nature into Built Environments',
        'Conceptualizing biophilic design to integrate nature within urban structures.',
        '2024-05-08',
        '1.0',
        'PUBLISHED',
        '42',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication65',
        160
    ),
    (
        66,
        '66',
        '66',
        'Mathematics',
        'TOPIC_66',
        'Algebraic Structures in Cryptography',
        'An overview of algebraic structures and their applications in cryptography.',
        '2024-05-20',
        '1.3',
        'ACCEPTED',
        '39',
        'English',
        'CC BY 4.0',
        'https://example.com/publication66',
        140
    ),
    (
        67,
        '67',
        '67',
        'Chemistry',
        'TOPIC_67',
        'Green Chemistry: Innovations for Sustainable Processes',
        'Discussion on sustainable innovations in green chemistry to minimize environmental impact.',
        '2024-06-05',
        '1.0',
        'DRAFT',
        '40',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication67',
        150
    ),
    (
        68,
        '68',
        '68',
        'Zoology',
        'TOPIC_68',
        'Marine Biodiversity: Conservation and Challenges',
        'Insights into the conservation challenges faced by marine biodiversity.',
        '2024-06-18',
        '1.1',
        'PUBLISHED',
        '36',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication68',
        220
    ),
    (
        69,
        '69',
        '69',
        'Physics',
        'TOPIC_69',
        'Quantum Mechanics: Paradigm Shifts and Applications',
        'An exploration of paradigm shifts and applications within quantum mechanics.',
        '2024-07-30',
        '2.0',
        'UNDER_REVIEW',
        '41',
        'English',
        'CC BY 4.0',
        'https://example.com/publication69',
        170
    ),
    (
        70,
        '70',
        '70',
        'History',
        'TOPIC_70',
        'World War II: Strategic Analysis and Impacts',
        'A detailed strategic analysis of World War II and its long-lasting impacts.',
        '2024-08-12',
        '1.2',
        'RETRACTED',
        '45',
        'English',
        'CC BY-NC-SA 4.0',
        'https://example.com/publication70',
        80
    ),
    (
        71,
        '71',
        '71',
        'Humanities',
        'TOPIC_71',
        'Cultural Identity in the Globalization Era',
        'How cultural identity is reshaping in the era of globalization and transnationalism.',
        '2024-08-26',
        '1.0',
        'PUBLISHED',
        '33',
        'English',
        'CC BY 4.0',
        'https://example.com/publication71',
        120
    ),
    (
        72,
        '72',
        '72',
        'Industrial Design',
        'TOPIC_72',
        'User-Centric Design: Enhancing Product Usability',
        'A study on principles and applications of user-centric design in industrial products.',
        '2024-09-14',
        '1.1',
        'ACCEPTED',
        '37',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication72',
        190
    ),
    (
        73,
        '73',
        '73',
        'Economics',
        'TOPIC_73',
        'Cryptocurrency: Economic Implications and Regulatory Challenges',
        'Exploring economic implications and regulatory challenges posed by cryptocurrency.',
        '2024-09-27',
        '2.0',
        'DRAFT',
        '43',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication73',
        230
    ),
    (
        74,
        '74',
        '74',
        'Ethics',
        'TOPIC_74',
        'Bioethics in Genetic Engineering',
        'Evaluating ethical considerations in the development of genetic engineering technologies.',
        '2024-10-05',
        '1.2',
        'SUBMITTED',
        '31',
        'English',
        'CC BY 4.0',
        'https://example.com/publication74',
        150
    ),
    (
        75,
        '75',
        '75',
        'Astronomy',
        'TOPIC_75',
        'Exoplanets: Exploring New Worlds Beyond Our Solar System',
        'Discoveries and research focused on exoplanets and habitable conditions beyond Earth.',
        '2024-10-18',
        '1.0',
        'PUBLISHED',
        '39',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication75',
        250
    ),
    (
        76,
        '76',
        '76',
        'Medicine',
        'TOPIC_76',
        'Telemedicine: Shaping the Future of Healthcare',
        'An investigative look into how telemedicine is transforming healthcare delivery.',
        '2024-11-02',
        '1.0',
        'ACCEPTED',
        '34',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication76',
        200
    ),
    (
        77,
        '77',
        '77',
        'Law',
        'TOPIC_77',
        'Cybersecurity Laws: Evolution and Challenges',
        'Exploring the evolution and ongoing challenges faced in the realm of cybersecurity law.',
        '2024-11-16',
        '1.3',
        'PUBLISHED',
        '46',
        'English',
        'CC BY 4.0',
        'https://example.com/publication77',
        310
    ),
    (
        78,
        '78',
        '78',
        'Finance',
        'TOPIC_78',
        'Digital Currencies: The Future of Money?',
        'Analyzing the future of money with the rise of digital currencies worldwide.',
        '2024-12-01',
        '1.1',
        'UNDER_REVIEW',
        '36',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication78',
        180
    ),
    (
        79,
        '79',
        '79',
        'Neuroscience',
        'TOPIC_79',
        'Neurodegenerative Diseases: Advances in Treatment',
        'Evaluating recent advances in the treatment of neurodegenerative diseases.',
        '2024-12-14',
        '2.0',
        'DRAFT',
        '29',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication79',
        200
    ),
    (
        80,
        '80',
        '80',
        'Public Health',
        'TOPIC_80',
        'Global Health Initiatives: Progress and Challenges',
        'A critical overview of global health initiatives and ongoing challenges.',
        '2025-01-05',
        '1.2',
        'RETRACTED',
        '40',
        'English',
        'CC BY 4.0',
        'https://example.com/publication80',
        95
    ),
    (
        81,
        '81',
        '81',
        'Environmental Science',
        'TOPIC_81',
        'Urban Pollution: Solutions and Strategies',
        'Analyzing strategies aimed at reducing urban pollution in metropolitan areas.',
        '2025-01-19',
        '1.0',
        'PUBLISHED',
        '38',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication81',
        170
    ),
    (
        82,
        '82',
        '82',
        'Bibliometrics',
        'TOPIC_82',
        'Measuring Scientific Impact: Metrics and Misconceptions',
        'Discussion on different metrics to measure scientific impact and their potential misconceptions.',
        '2025-02-07',
        '1.1',
        'SUBMITTED',
        '32',
        'English',
        'CC BY 4.0',
        'https://example.com/publication82',
        140
    ),
    (
        83,
        '83',
        '83',
        'Pharmaceutical Sciences',
        'TOPIC_83',
        'Pharmacogenomics: Personalized Approaches to Drug Therapy',
        'Exploring personalized approaches to drug therapy through pharmacogenomics.',
        '2025-02-20',
        '1.0',
        'PUBLISHED',
        '35',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication83',
        210
    ),
    (
        84,
        '84',
        '84',
        'Oceanography',
        'TOPIC_84',
        'Deep Sea Exploration: Discoveries and Technologies',
        'Technologies driving discoveries in deep-sea exploration and marine research.',
        '2025-03-12',
        '1.3',
        'UNDER_REVIEW',
        '41',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication84',
        160
    ),
    (
        85,
        '85',
        '85',
        'Cognitive Science',
        'TOPIC_85',
        'The Science of Consciousness: Current Research and Debates',
        'Current research and debates concerning the science of consciousness.',
        '2025-03-29',
        '1.0',
        'DRAFT',
        '30',
        'English',
        'CC BY 4.0',
        'https://example.com/publication85',
        130
    ),
    (
        86,
        '86',
        '86',
        'Linguistics',
        'TOPIC_86',
        'Semantics and Pragmatics: Language in Context',
        'Investigating semantics and pragmatics as vital aspects of language in context.',
        '2025-04-18',
        '1.1',
        'ACCEPTED',
        '34',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication86',
        250
    ),
    (
        87,
        '87',
        '87',
        'Musicology',
        'TOPIC_87',
        'Digital Music Production: Techniques and Tools',
        'A comprehensive guide to contemporary techniques and tools in digital music production.',
        '2025-05-03',
        '2.0',
        'SUBMITTED',
        '42',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication87',
        140
    ),
    (
        88,
        '88',
        '88',
        'Anthropology',
        'TOPIC_88',
        'Human Migration: Historical and Contemporary Perspectives',
        'A look into historical and contemporary perspectives on human migration.',
        '2025-05-20',
        '1.2',
        'PUBLISHED',
        '37',
        'English',
        'CC BY 4.0',
        'https://example.com/publication88',
        110
    ),
    (
        89,
        '89',
        '89',
        'Archaeology',
        'TOPIC_89',
        'Ancient Civilizations: Evidence and Interpretation',
        'Interpreting evidence from archaeological findings about ancient civilizations.',
        '2025-06-06',
        '1.0',
        'PUBLISHED',
        '38',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication89',
        220
    ),
    (
        90,
        '90',
        '90',
        'Epistemology',
        'TOPIC_90',
        'Knowledge and Belief: A Philosophical Inquiry',
        'Philosophical discussions exploring the relationship between knowledge and belief.',
        '2025-06-23',
        '1.3',
        'RETRACTED',
        '41',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication90',
        90
    ),
    (
        91,
        '91',
        '91',
        'Forestry',
        'TOPIC_91',
        'Forest Management Practices: Sustainability and Conservation',
        'Exploration of sustainable forest management and conservation practices globally.',
        '2025-07-15',
        '1.0',
        'DRAFT',
        '36',
        'English',
        'CC BY 4.0',
        'https://example.com/publication91',
        180
    ),
    (
        92,
        '92',
        '92',
        'Aquatic Sciences',
        'TOPIC_92',
        'The Freshwater Ecosystems: Threats and Protection Strategies',
        'Evaluation of threats to freshwater ecosystems and protection strategies.',
        '2025-08-01',
        '1.1',
        'UNDER_REVIEW',
        '33',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication92',
        150
    ),
    (
        93,
        '93',
        '93',
        'Urban Studies',
        'TOPIC_93',
        'Sustainable Urbanization: Challenges and Opportunities',
        'Challenges and opportunities for achieving sustainable urbanization.',
        '2025-08-18',
        '2.0',
        'ACCEPTED',
        '35',
        'English',
        'CC BY 4.0',
        'https://example.com/publication93',
        95
    ),
    (
        94,
        '94',
        '94',
        'Theoretical Physics',
        'TOPIC_94',
        'String Theory: Unraveling the Universe',
        'Discussing the implications and developments in string theory for cosmology.',
        '2025-09-03',
        '1.2',
        'PUBLISHED',
        '32',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication94',
        190
    ),
    (
        95,
        '95',
        '95',
        'Botany',
        'TOPIC_95',
        'Plant Genetics: Breeding for Resilience and Yield',
        'Research into plant genetics aimed at improving resilience and crop yield.',
        '2025-09-20',
        '1.0',
        'SUBMITTED',
        '31',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication95',
        210
    ),
    (
        96,
        '96',
        '96',
        'Food Science',
        'TOPIC_96',
        'Food Safety Innovations: Ensuring Global Standards',
        'A look at innovations in food safety aimed at ensuring global standards.',
        '2025-10-10',
        '1.3',
        'RETRACTED',
        '39',
        'English',
        'CC BY 4.0',
        'https://example.com/publication96',
        230
    ),
    (
        97,
        '97',
        '97',
        'Cultural Studies',
        'TOPIC_97',
        'The Influence of Pop Culture on Modern Society',
        'Investigating how pop culture influences social values and norms today.',
        '2025-10-28',
        '1.1',
        'ACCEPTED',
        '37',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication97',
        160
    ),
    (
        98,
        '98',
        '98',
        'Astronomy',
        'TOPIC_98',
        'Black Holes: Theories and Observations',
        'An examination of current theories and observational data on black holes.',
        '2025-11-15',
        '2.0',
        'PUBLISHED',
        '44',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication98',
        180
    ),
    (
        99,
        '99',
        '99',
        'Cybernetics',
        'TOPIC_99',
        'Cyber-Physical Systems: Integration and Application',
        'Exploration of integrating cyber-physical systems for advanced technological applications.',
        '2025-11-30',
        '1.2',
        'UNDER_REVIEW',
        '40',
        'English',
        'CC BY 4.0',
        'https://example.com/publication99',
        95
    ),
    (
        100,
        '100',
        '100',
        'Paleobotany',
        'TOPIC_100',
        'Fossil Plants: Tracing the History of Flora',
        'Insights from fossil plants provide information about the history of flora.',
        '2025-12-18',
        '1.0',
        'PUBLISHED',
        '35',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication100',
        105
    ),
    (
        101,
        '101',
        '101',
        'Meteorology',
        'TOPIC_101',
        'Climate Change Modeling: Advances and Challenges',
        'An overview of recent advances and ongoing challenges in climate change modeling.',
        '2026-01-05',
        '1.1',
        'SUBMITTED',
        '46',
        'English',
        'CC BY 4.0',
        'https://example.com/publication101',
        175
    ),
    (
        102,
        '102',
        '102',
        'Robotics',
        'TOPIC_102',
        'Autonomous Robotics: Navigating Complex Environments',
        'Exploration of autonomous robotic systems and their ability to navigate complex environments.',
        '2026-01-20',
        '1.0',
        'PUBLISHED',
        '39',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication102',
        205
    ),
    (
        103,
        '103',
        '103',
        'Philosophy',
        'TOPIC_103',
        'The Nature of Consciousness: A Philosophical Perspective',
        'Philosophical discussions on the nature and understanding of consciousness.',
        '2026-02-14',
        '1.2',
        'UNDER_REVIEW',
        '37',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication103',
        90
    ),
    (
        104,
        '104',
        '104',
        'Ethnography',
        'TOPIC_104',
        'Ethnographic Research Methods in the Digital Age',
        'Adapting ethnographic research methods to the digital landscape.',
        '2026-02-27',
        '1.0',
        'DRAFT',
        '31',
        'English',
        'CC BY 4.0',
        'https://example.com/publication104',
        110
    ),
    (
        105,
        '105',
        '105',
        'Microbiology',
        'TOPIC_105',
        'Antimicrobial Resistance: Strategies for Control',
        'Reviewing strategies to control and mitigate antimicrobial resistance globally.',
        '2026-03-10',
        '1.3',
        'ACCEPTED',
        '35',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication105',
        160
    ),
    (
        106,
        '106',
        '106',
        'Geography',
        'TOPIC_106',
        'GIS and Remote Sensing: Tools for Environmental Monitoring',
        'Exploring the application of GIS and remote sensing in environmental monitoring.',
        '2026-03-25',
        '1.1',
        'PUBLISHED',
        '40',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication106',
        140
    ),
    (
        107,
        '107',
        '107',
        'Genetics',
        'TOPIC_107',
        'CRISPR: Ethical and Practical Implications',
        'Discussion about the ethical and practical implications of CRISPR technology in genetics.',
        '2026-04-12',
        '1.0',
        'SUBMITTED',
        '36',
        'English',
        'CC BY 4.0',
        'https://example.com/publication107',
        190
    ),
    (
        108,
        '108',
        '108',
        'Linguistics',
        'TOPIC_108',
        'Bilingualism: Cognitive Benefits and Challenges',
        'An exploration of cognitive benefits and challenges associated with bilingualism.',
        '2026-05-01',
        '1.2',
        'UNDER_REVIEW',
        '34',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication108',
        190
    ),
    (
        109,
        '109',
        '109',
        'Psychiatry',
        'TOPIC_109',
        'Mental Health: Innovations in Therapy and Treatment',
        'Exploring new therapies and treatments in the field of mental health.',
        '2026-05-20',
        '1.0',
        'PUBLISHED',
        '37',
        'English',
        'CC BY 4.0',
        'https://example.com/publication109',
        210
    ),
    (
        110,
        '110',
        '110',
        'Sports Science',
        'TOPIC_110',
        'Sports Analytics: Data-Driven Performance',
        'The role of data analytics in optimizing athlete performance and training.',
        '2026-06-06',
        '1.3',
        'DRAFT',
        '33',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication110',
        150
    ),
    (
        111,
        '111',
        '111',
        'Art History',
        'TOPIC_111',
        'Renaissance Art: Interpretation and Influence',
        'Analysing the interpretation and influence of Renaissance art in modern times.',
        '2026-06-20',
        '1.1',
        'SUBMITTED',
        '35',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication111',
        125
    ),
    (
        112,
        '112',
        '112',
        'Data Science',
        'TOPIC_112',
        'Big Data Applications: Trends and Innovations',
        'Trends and innovations transforming industries with the use of big data.',
        '2026-07-04',
        '1.2',
        'ACCEPTED',
        '47',
        'English',
        'CC BY 4.0',
        'https://example.com/publication112',
        230
    ),
    (
        113,
        '113',
        '113',
        'Human Rights',
        'TOPIC_113',
        'Human Rights in the Digital World',
        'Challenges and developments in human rights protections in the digital age.',
        '2026-07-19',
        '1.0',
        'PUBLISHED',
        '36',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication113',
        95
    ),
    (
        114,
        '114',
        '114',
        'Engineering',
        'TOPIC_114',
        'Sustainable Engineering Practices',
        'Adopting sustainable practices in engineering for environmental conservation.',
        '2026-08-14',
        '2.0',
        'UNDER_REVIEW',
        '45',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication114',
        260
    ),
    (
        115,
        '115',
        '115',
        'Behavioral Science',
        'TOPIC_115',
        'Behavioral Economics: Insights and Applications',
        'Insights into behavioral economics and their applications in real-world scenarios.',
        '2026-08-29',
        '1.1',
        'PUBLISHED',
        '38',
        'English',
        'CC BY 4.0',
        'https://example.com/publication115',
        180
    ),
    (
        116,
        '116',
        '116',
        'Hydrology',
        'TOPIC_116',
        'Water Resource Management: Strategies and Challenges',
        'Analyzing strategies and challenges in effective water resource management.',
        '2026-09-12',
        '1.0',
        'ACCEPTED',
        '36',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication116',
        150
    ),
    (
        117,
        '117',
        '117',
        'Media Studies',
        'TOPIC_117',
        'Social Media Influence on Public Opinion',
        'Examining how social media platforms influence public discourse and opinion.',
        '2026-09-30',
        '1.2',
        'SUBMITTED',
        '32',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication117',
        205
    ),
    (
        118,
        '118',
        '118',
        'Nanotechnology',
        'TOPIC_118',
        'Nanotechnology and Environmental Impact Assessments',
        'Evaluating environmental impacts and assessments of nanotechnological advances.',
        '2026-10-15',
        '1.3',
        'PUBLISHED',
        '40',
        'English',
        'CC BY 4.0',
        'https://example.com/publication118',
        290
    ),
    (
        119,
        '119',
        '119',
        'Bioinformatics',
        'TOPIC_119',
        'Computational Biology: Emerging Techniques and Applications',
        'Emerging techniques in computational biology and their wide applications.',
        '2026-11-05',
        '1.1',
        'UNDER_REVIEW',
        '34',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication119',
        230
    ),
    (
        120,
        '120',
        '120',
        'Psychotherapy',
        'TOPIC_120',
        'Therapeutic Techniques for Anxiety Disorders',
        'An in-depth look into contemporary therapeutic techniques used for treating anxiety disorders.',
        '2026-11-20',
        '1.0',
        'DRAFT',
        '33',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication120',
        140
    ),
    (
        121,
        '121',
        '121',
        'Cognitive Neuroscience',
        'TOPIC_121',
        'Brain Plasticity: New Insights and Research',
        'Exploring new insights and research into the phenomena of brain plasticity.',
        '2026-12-02',
        '1.0',
        'ACCEPTED',
        '40',
        'English',
        'CC BY 4.0',
        'https://example.com/publication121',
        170
    ),
    (
        122,
        '122',
        '122',
        'Criminology',
        'TOPIC_122',
        'Crime Analysis: Patterns and Predictive Models',
        'Exploring patterns and predictive models in crime analysis for law enforcement.',
        '2026-12-18',
        '2.0',
        'SUBMITTED',
        '42',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication122',
        200
    ),
    (
        123,
        '123',
        '123',
        'Psychology',
        'TOPIC_123',
        'The Psychology of Decision-Making',
        'Understanding the psychological processes involved in decision-making.',
        '2027-01-10',
        '1.2',
        'PUBLISHED',
        '48',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication123',
        260
    ),
    (
        124,
        '124',
        '124',
        'Sociology',
        'TOPIC_124',
        'Digital Society: Changing Interpersonal Dynamics',
        'Investigating changes in interpersonal dynamics within digital societies.',
        '2027-01-25',
        '1.0',
        'UNDER_REVIEW',
        '30',
        'English',
        'CC BY 4.0',
        'https://example.com/publication124',
        150
    ),
    (
        125,
        '125',
        '125',
        'Biomedical Sciences',
        'TOPIC_125',
        'Emerging Trends in Biomedical Engineering',
        'Exploring emerging trends and innovations in the field of biomedical engineering.',
        '2027-02-13',
        '1.1',
        'PUBLISHED',
        '41',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication125',
        300
    ),
    (
        126,
        '126',
        '126',
        'International Relations',
        'TOPIC_126',
        'Global Politics: The Role of International Institutions',
        'Analyzing the role and influence of international institutions in global politics.',
        '2027-02-28',
        '1.3',
        'ACCEPTED',
        '29',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication126',
        190
    ),
    (
        127,
        '127',
        '127',
        'Oceanography',
        'TOPIC_127',
        'Coral Reefs: Conservation and Restoration Techniques',
        'Investigating conservation and restoration techniques for coral reef ecosystems.',
        '2027-03-17',
        '1.2',
        'DRAFT',
        '35',
        'English',
        'CC BY 4.0',
        'https://example.com/publication127',
        240
    ),
    (
        128,
        '128',
        '128',
        'Zoology',
        'TOPIC_128',
        'Wildlife Conservation: Policies and Practices',
        'Review of policies and best practices in wildlife conservation across the world.',
        '2027-04-03',
        '1.0',
        'UNDER_REVIEW',
        '34',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication128',
        130
    ),
    (
        129,
        '129',
        '129',
        'Astronomy',
        'TOPIC_129',
        'The Cosmic Microwave Background: Insights into the Early Universe',
        'Research on the cosmic microwave background and its implications for understanding the early universe.',
        '2027-04-18',
        '1.1',
        'PUBLISHED',
        '39',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication129',
        280
    ),
    (
        130,
        '130',
        '130',
        'Robotics',
        'TOPIC_130',
        'Swarm Robotics: Coordination and Control',
        'Study on coordination and control mechanisms in swarm robotics.',
        '2027-05-10',
        '1.3',
        'ACCEPTED',
        '31',
        'English',
        'CC BY 4.0',
        'https://example.com/publication130',
        165
    ),
    (
        131,
        '131',
        '131',
        'Art',
        'TOPIC_131',
        'The Evolution of Modern Art Movements',
        'An exploration of various movements that have shaped modern art.',
        '2027-05-24',
        '2.0',
        'PUBLISHED',
        '45',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication131',
        125
    ),
    (
        132,
        '132',
        '132',
        'Information Technology',
        'TOPIC_132',
        'Cloud Computing: Infrastructure and Security',
        'Evaluation of infrastructure and security challenges within cloud computing technologies.',
        '2027-06-09',
        '1.2',
        'DRAFT',
        '43',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication132',
        240
    ),
    (
        133,
        '133',
        '133',
        'Environmental Engineering',
        'TOPIC_133',
        'Waste Management: Recycling Technologies and Policies',
        'Investigating recycling technologies and policies for efficient waste management.',
        '2027-06-30',
        '1.0',
        'SUBMITTED',
        '36',
        'English',
        'CC BY 4.0',
        'https://example.com/publication133',
        220
    ),
    (
        134,
        '134',
        '134',
        'Cyber Security',
        'TOPIC_134',
        'Advanced Threat Detection in Cybersecurity',
        'Overview of advanced threat detection techniques in cybersecurity systems.',
        '2027-07-11',
        '1.1',
        'UNDER_REVIEW',
        '32',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication134',
        200
    ),
    (
        135,
        '135',
        '135',
        'Physics',
        'TOPIC_135',
        'Fundamental Forces in the Universe: A Unified Theory?',
        'Assessing theories potential for unifying fundamental forces in physics.',
        '2027-07-27',
        '1.2',
        'PUBLISHED',
        '40',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication135',
        265
    ),
    (
        136,
        '136',
        '136',
        'Linguistics',
        'TOPIC_136',
        'Language Acquisition: Theories and Practices',
        'Evaluating theories and practices of language acquisition in humans.',
        '2027-08-09',
        '1.0',
        'ACCEPTED',
        '33',
        'English',
        'CC BY 4.0',
        'https://example.com/publication136',
        195
    ),
    (
        137,
        '137',
        '137',
        'Materials Science',
        'TOPIC_137',
        'Biodegradable Materials: Progress and Potential',
        'An exploration of biodegradable materials progress and their potential applications.',
        '2027-08-25',
        '1.3',
        'SUBMITTED',
        '37',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication137',
        180
    ),
    (
        138,
        '138',
        '138',
        'Urban Planning',
        'TOPIC_138',
        'Transportation Systems for Future Cities',
        'Innovative transportation systems designed for sustainability in future urban environments.',
        '2027-09-14',
        '1.1',
        'PUBLISHED',
        '35',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication138',
        230
    ),
    (
        139,
        '139',
        '139',
        'Neuroscience',
        'TOPIC_139',
        'Brain-Computer Interfaces: Current Developments',
        'Examining the current state of research and development in brain-computer interfaces.',
        '2027-10-01',
        '2.0',
        'DRAFT',
        '39',
        'English',
        'CC BY 4.0',
        'https://example.com/publication139',
        150
    ),
    (
        140,
        '140',
        '140',
        'Social Work',
        'TOPIC_140',
        'Community-Based Solutions: Empowering Local Initiatives',
        'Exploring community-based solutions and the empowerment of local initiatives.',
        '2027-10-25',
        '1.2',
        'UNDER_REVIEW',
        '44',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication140',
        120
    ),
    (
        141,
        '141',
        '141',
        'Nuclear Physics',
        'TOPIC_141',
        'Fusion Energy: Achieving Sustainable Power',
        'Research focused on advancements toward sustainable power through fusion energy technologies.',
        '2027-11-10',
        '1.0',
        'PUBLISHED',
        '38',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication141',
        250
    ),
    (
        142,
        '142',
        '142',
        'Literature',
        'TOPIC_142',
        'Contemporary Literature: Trends and Themes',
        'Analyzing recent trends and themes in contemporary literature.',
        '2027-11-30',
        '1.1',
        'ACCEPTED',
        '31',
        'English',
        'CC BY 4.0',
        'https://example.com/publication142',
        180
    ),
    (
        143,
        '143',
        '143',
        'Biochemistry',
        'TOPIC_143',
        'Protein Folding: Mechanisms and Diseases',
        'Reviewing the mechanisms of protein folding and associated diseases.',
        '2027-12-15',
        '1.0',
        'UNDER_REVIEW',
        '30',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication143',
        160
    ),
    (
        144,
        '144',
        '144',
        'Machine Learning',
        'TOPIC_144',
        'Deep Learning Algorithms: Innovations and Challenges',
        'Challenges and innovations in the development of deep learning algorithms.',
        '2028-01-06',
        '1.3',
        'ACCEPTED',
        '34',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication144',
        280
    ),
    (
        145,
        '145',
        '145',
        'Chemistry',
        'TOPIC_145',
        'Catalysis: Driving Green Chemistry Forward',
        'Exploration of advancements in catalysis driving sustainable practices in green chemistry.',
        '2028-01-20',
        '1.2',
        'PUBLISHED',
        '42',
        'English',
        'CC BY 4.0',
        'https://example.com/publication145',
        310
    ),
    (
        146,
        '146',
        '146',
        'Astrophysics',
        'TOPIC_146',
        'Dark Matter and Dark Energy: Unveiling the Mysteries',
        'Research focused on understanding dark matter and dark energy in the universe.',
        '2028-02-10',
        '1.1',
        'DRAFT',
        '37',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication146',
        190
    ),
    (
        147,
        '147',
        '147',
        'Education',
        'TOPIC_147',
        'Collaborative Learning Environments: Benefits and Challenges',
        'Analysis of the benefits and challenges of collaborative learning environments.',
        '2028-03-05',
        '2.0',
        'SUBMITTED',
        '33',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication147',
        160
    ),
    (
        148,
        '148',
        '148',
        'Psychiatry',
        'TOPIC_148',
        'Trauma-Informed Care: A Therapeutic Approach',
        'Exploring trauma-informed care as an effective therapeutic approach in psychiatry.',
        '2028-03-20',
        '1.0',
        'ACCEPTED',
        '31',
        'English',
        'CC BY 4.0',
        'https://example.com/publication148',
        170
    ),
    (
        149,
        '149',
        '149',
        'Economics',
        'TOPIC_149',
        'Game Theory in Economics: Modern Applications',
        'Modern applications of game theory in economic analysis and decision-making.',
        '2028-04-04',
        '1.3',
        'UNDER_REVIEW',
        '44',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication149',
        120
    ),
    (
        150,
        '150',
        '150',
        'Cognitive Science',
        'TOPIC_150',
        'Implicit Bias: Understanding and Mitigation',
        'A study on understanding and mitigating implicit biases in cognitive processes.',
        '2028-04-27',
        '1.3',
        'PUBLISHED',
        '36',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication150',
        200
    ),
    (
        151,
        '151',
        '151',
        'Blockchain',
        'TOPIC_151',
        'Blockchain in Supply Chain: Transparency and Trust',
        'Evaluating the role of blockchain technologies in enhancing transparency and trust within supply chains.',
        '2028-05-10',
        '1.2',
        'PUBLISHED',
        '41',
        'English',
        'CC BY 4.0',
        'https://example.com/publication151',
        210
    ),
    (
        152,
        '152',
        '152',
        'Climate Science',
        'TOPIC_152',
        'Climate Adaptation: Policy and Practice',
        'An overview of policy and practical approaches to climate adaptation.',
        '2028-05-25',
        '1.0',
        'UNDER_REVIEW',
        '35',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication152',
        180
    ),
    (
        153,
        '153',
        '153',
        'Renewable Energy',
        'TOPIC_153',
        'Solar Energy: Advances in Photovoltaic Technology',
        'Research on recent advances in photovoltaic technology for enhanced solar energy capture.',
        '2028-06-05',
        '1.1',
        'ACCEPTED',
        '36',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication153',
        240
    ),
    (
        154,
        '154',
        '154',
        'Quantum Computing',
        'TOPIC_154',
        'Quantum Algorithms: Opportunities and Challenges',
        'Exploration of emerging opportunities and challenges in quantum algorithm development.',
        '2028-06-22',
        '1.3',
        'PUBLISHED',
        '42',
        'English',
        'CC BY 4.0',
        'https://example.com/publication154',
        300
    ),
    (
        155,
        '155',
        '155',
        'Anthropology',
        'TOPIC_155',
        'Cultural Anthropology: Evolutionary Perspectives',
        'An investigation into evolutionary perspectives in cultural anthropology.',
        '2028-07-12',
        '1.1',
        'DRAFT',
        '39',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication155',
        135
    ),
    (
        156,
        '156',
        '156',
        'Sustainability',
        'TOPIC_156',
        'Circular Economy: Principles and Implementation',
        'Implementing circular economy principles for global sustainability.',
        '2028-07-30',
        '1.0',
        'SUBMITTED',
        '31',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication156',
        145
    ),
    (
        157,
        '157',
        '157',
        'Ethics',
        'TOPIC_157',
        'Ethical AI: Balancing Innovation and Accountability',
        'Discussing ethical considerations and accountability in AI development and deployment.',
        '2028-08-07',
        '1.2',
        'UNDER_REVIEW',
        '38',
        'English',
        'CC BY 4.0',
        'https://example.com/publication157',
        190
    ),
    (
        158,
        '158',
        '158',
        'Public Health',
        'TOPIC_158',
        'Epidemiology: Tracking and Controlling Disease Outbreaks',
        'Strategies and methods in epidemiology for tracking and controlling disease outbreaks.',
        '2028-08-25',
        '1.0',
        'ACCEPTED',
        '34',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication158',
        220
    ),
    (
        159,
        '159',
        '159',
        'Nutrition',
        'TOPIC_159',
        'Nutritional Genomics: Personalized Diets for Health',
        'The role of nutritional genomics in developing personalized diets for optimal health.',
        '2028-09-12',
        '1.1',
        'PUBLISHED',
        '32',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication159',
        175
    ),
    (
        160,
        '160',
        '160',
        'Cultural Studies',
        'TOPIC_160',
        'Digital Storytelling: New Narratives in a Digital Age',
        'Analysis of digital storytelling platforms and their impact on narrative forms.',
        '2028-09-26',
        '1.3',
        'DRAFT',
        '40',
        'English',
        'CC BY 4.0',
        'https://example.com/publication160',
        130
    ),
    (
        161,
        '161',
        '161',
        'Political Science',
        'TOPIC_161',
        'Populism: Causes and Effects in Global Politics',
        'An inquiry into the causes and effects of populism in global political dynamics.',
        '2028-10-11',
        '2.0',
        'SUBMITTED',
        '44',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication161',
        210
    ),
    (
        162,
        '162',
        '162',
        'Marine Biology',
        'TOPIC_162',
        'Ocean Acidification: Effects on Marine Biodiversity',
        'Assessing the effects of ocean acidification on marine biodiversity and ecosystems.',
        '2028-10-29',
        '1.1',
        'UNDER_REVIEW',
        '37',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication162',
        195
    ),
    (
        163,
        '163',
        '163',
        'Archeology',
        'TOPIC_163',
        'Digital Archaeology: Technological Innovations',
        'Technological innovations enhancing archaeological research and data analysis.',
        '2028-11-12',
        '1.0',
        'PUBLISHED',
        '35',
        'English',
        'CC BY 4.0',
        'https://example.com/publication163',
        145
    ),
    (
        164,
        '164',
        '164',
        'Pharmaceuticals',
        'TOPIC_164',
        'Pharmacogenomics: Tailoring Drug Therapies',
        'Personalizing drug therapies based on pharmacogenomics to improve patient outcomes.',
        '2029-01-03',
        '1.3',
        'ACCEPTED',
        '39',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication164',
        185
    ),
    (
        165,
        '165',
        '165',
        'Architecture',
        'TOPIC_165',
        'Biophilic Design: Integrating Nature and Architecture',
        'The principles and benefits of integrating nature into architectural designs.',
        '2029-01-19',
        '1.0',
        'DRAFT',
        '33',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication165',
        160
    ),
    (
        166,
        '166',
        '166',
        'Agricultural Science',
        'TOPIC_166',
        'Precision Agriculture: Enhancing Crop Production',
        'How precision agriculture technologies are enhancing crop production efficiency and sustainability.',
        '2029-02-02',
        '1.2',
        'SUBMITTED',
        '38',
        'English',
        'CC BY 4.0',
        'https://example.com/publication166',
        175
    ),
    (
        167,
        '167',
        '167',
        'Social Sciences',
        'TOPIC_167',
        'Social Networks: Impact on Human Interaction',
        'Exploring the impact of social networks on human social interaction and communication.',
        '2029-02-18',
        '1.1',
        'UNDER_REVIEW',
        '34',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication167',
        230
    ),
    (
        168,
        '168',
        '168',
        'Geology',
        'TOPIC_168',
        'Volcano Monitoring: Technologies and Innovations',
        'Monitoring technologies and innovations in the study of volcanic activities.',
        '2029-03-05',
        '1.0',
        'ACCEPTED',
        '36',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication168',
        190
    ),
    (
        169,
        '169',
        '169',
        'Financial Studies',
        'TOPIC_169',
        'Cryptocurrency Markets: Trends and Risks',
        'Analyzing trends and assessing risks in the dynamic cryptocurrency markets.',
        '2029-03-22',
        '1.3',
        'PUBLISHED',
        '32',
        'English',
        'CC BY 4.0',
        'https://example.com/publication169',
        250
    ),
    (
        170,
        '170',
        '170',
        'Education Technology',
        'TOPIC_170',
        'E-Learning Platforms: Adoption and Impact',
        'The adoption and impact of e-learning platforms in education systems worldwide.',
        '2029-04-07',
        '1.2',
        'DRAFT',
        '48',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication170',
        200
    ),
    (
        171,
        '171',
        '171',
        'Biotechnology',
        'TOPIC_171',
        'Gene Editing: Potential and Ethical Considerations',
        'Exploration of potential applications and ethical considerations in gene editing.',
        '2029-04-30',
        '1.1',
        'SUBMITTED',
        '30',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication171',
        215
    ),
    (
        172,
        '172',
        '172',
        'Neural Networks',
        'TOPIC_172',
        'Neural Networks in Artificial Intelligence: Future Directions',
        'Research on the future directions of neural networks within the field of artificial intelligence.',
        '2029-05-15',
        '1.0',
        'UNDER_REVIEW',
        '37',
        'English',
        'CC BY 4.0',
        'https://example.com/publication172',
        310
    ),
    (
        173,
        '173',
        '173',
        'Transportation Studies',
        'TOPIC_173',
        'Autonomous Vehicles: Safety and Software Challenges',
        'Identifying safety and software challenges in the development of autonomous vehicles.',
        '2029-06-03',
        '1.3',
        'ACCEPTED',
        '33',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication173',
        225
    ),
    (
        174,
        '174',
        '174',
        'Urban Studies',
        'TOPIC_174',
        'Smart Cities: Integrating Technology and Society',
        'Overview of integrating technology into urban planning to build smart and sustainable cities.',
        '2029-06-25',
        '2.0',
        'PUBLISHED',
        '47',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication174',
        245
    ),
    (
        175,
        '175',
        '175',
        'Theology',
        'TOPIC_175',
        'Comparative Religion: Dialogues and Debates',
        'Investigating dialogues and debates in comparative religion studies.',
        '2029-07-12',
        '1.1',
        'DRAFT',
        '39',
        'English',
        'CC BY 4.0',
        'https://example.com/publication175',
        105
    ),
    (
        176,
        '176',
        '176',
        'Behavioral Genetics',
        'TOPIC_176',
        'Genetic Influences on Behavior: Current Research',
        'A review of current research on the genetic influences on human behavior.',
        '2029-07-29',
        '1.0',
        'SUBMITTED',
        '36',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication176',
        175
    ),
    (
        177,
        '177',
        '177',
        'Sociolinguistics',
        'TOPIC_177',
        'Language and Identity: Social and Cultural Perspectives',
        'Exploring the relationship between language and identity across social and cultural perspectives.',
        '2029-08-16',
        '1.2',
        'UNDER_REVIEW',
        '35',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication177',
        140
    ),
    (
        178,
        '178',
        '178',
        'Fashion Studies',
        'TOPIC_178',
        'Sustainable Fashion: Trends and Innovations',
        'An examination of sustainability trends and technological innovations in the fashion industry.',
        '2029-09-01',
        '1.1',
        'ACCEPTED',
        '43',
        'English',
        'CC BY 4.0',
        'https://example.com/publication178',
        190
    ),
    (
        179,
        '179',
        '179',
        'Meteorology',
        'TOPIC_179',
        'Extreme Weather Patterns: Prediction and Preparedness',
        'Research on predicting extreme weather patterns and enhancing preparedness strategies.',
        '2029-09-22',
        '1.3',
        'PUBLISHED',
        '37',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication179',
        260
    ),
    (
        180,
        '180',
        '180',
        'Artificial Intelligence',
        'TOPIC_180',
        'Ethical Dimensions of Machine Learning: Societal Impact',
        'Evaluating ethical dimensions and societal impacts of machine learning technologies.',
        '2029-10-05',
        '2.0',
        'DRAFT',
        '32',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication180',
        170
    ),
    (
        181,
        '181',
        '181',
        'Pediatric Medicine',
        'TOPIC_181',
        'Child Development: Current Approaches in Pediatrics',
        'Survey of current approaches to child development in pediatric medicine.',
        '2029-10-20',
        '1.0',
        'SUBMITTED',
        '30',
        'English',
        'CC BY 4.0',
        'https://example.com/publication181',
        155
    ),
    (
        182,
        '182',
        '182',
        'Linguistic Anthropology',
        'TOPIC_182',
        'Language in Culture: Anthropological Perspectives',
        'Examination of language use in cultural settings from an anthropological perspective.',
        '2029-11-01',
        '1.2',
        'UNDER_REVIEW',
        '41',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication182',
        160
    ),
    (
        183,
        '183',
        '183',
        'Econometrics',
        'TOPIC_183',
        'Applied Econometrics: Techniques and Applications',
        'Exploration of advanced techniques and practical applications in applied econometrics.',
        '2029-11-14',
        '1.1',
        'ACCEPTED',
        '34',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication183',
        220
    ),
    (
        184,
        '184',
        '184',
        'Cognitive Psychology',
        'TOPIC_184',
        'Memory and Cognition: Modern Approaches',
        'An analysis of modern approaches to memory and cognition in cognitive psychology.',
        '2029-11-30',
        '1.0',
        'PUBLISHED',
        '36',
        'English',
        'CC BY 4.0',
        'https://example.com/publication184',
        235
    ),
    (
        185,
        '185',
        '185',
        'Quantum Mechanics',
        'TOPIC_185',
        'Quantum Entanglement: Theoretical and Practical Aspects',
        'An examination of theoretical insights and practical applications in quantum entanglement.',
        '2029-12-10',
        '1.3',
        'DRAFT',
        '39',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication185',
        280
    ),
    (
        186,
        '186',
        '186',
        'Ecology',
        'TOPIC_186',
        'Ecosystem Services: Valuation and Management',
        'Methods for valuing and managing ecosystem services in ecological conservation.',
        '2029-12-22',
        '1.0',
        'SUBMITTED',
        '45',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication186',
        240
    ),
    (
        187,
        '187',
        '187',
        'Visual Arts',
        'TOPIC_187',
        'Digital Art: Techniques and Critiques',
        'Exploring the techniques and critiques of digital art across various mediums.',
        '2030-01-08',
        '1.1',
        'UNDER_REVIEW',
        '33',
        'English',
        'CC BY 4.0',
        'https://example.com/publication187',
        110
    ),
    (
        188,
        '188',
        '188',
        'Robotic Process Automation',
        'TOPIC_188',
        'RPA in Business: Efficiency and Workflow Optimization',
        'An overview of robotic process automation’s role in optimizing business efficiency and workflow.',
        '2030-01-20',
        '1.2',
        'ACCEPTED',
        '40',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication188',
        195
    ),
    (
        189,
        '189',
        '189',
        'Hydrogen Energy',
        'TOPIC_189',
        'Hydrogen Fuel Cells: Innovations in Energy Storage',
        'Advancements in hydrogen fuel cells for renewable energy storage solutions.',
        '2030-02-06',
        '1.0',
        'PUBLISHED',
        '36',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication189',
        270
    ),
    (
        190,
        '190',
        '190',
        'Marine Ecology',
        'TOPIC_190',
        'Coral Bleaching: Strategies for Conservation',
        'Exploring strategies for coral conservation in the face of widespread bleaching.',
        '2030-02-23',
        '1.3',
        'DRAFT',
        '32',
        'English',
        'CC BY 4.0',
        'https://example.com/publication190',
        165
    ),
    (
        191,
        '191',
        '191',
        'Environmental Policy',
        'TOPIC_191',
        'Carbon Emissions and Regulatory Frameworks',
        'Analyzing regulatory frameworks addressing carbon emissions on global and local scales.',
        '2030-03-15',
        '2.0',
        'SUBMITTED',
        '37',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication191',
        230
    ),
    (
        192,
        '192',
        '192',
        'Journalism',
        'TOPIC_192',
        'Digital Journalism: Ethics and Practices',
        'Assessing the ethics and evolving practices within digital journalism.',
        '2030-04-01',
        '1.1',
        'UNDER_REVIEW',
        '41',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication192',
        150
    ),
    (
        193,
        '193',
        '193',
        'Genomics',
        'TOPIC_193',
        'Whole-Genome Sequencing: Challenges and Solutions',
        'A deep dive into the challenges and technological solutions for whole-genome sequencing.',
        '2030-04-19',
        '1.0',
        'ACCEPTED',
        '39',
        'English',
        'CC BY 4.0',
        'https://example.com/publication193',
        260
    ),
    (
        194,
        '194',
        '194',
        'Cyber-Physical Systems',
        'TOPIC_194',
        'Security in Cyber-Physical Systems: Emerging Solutions',
        'Examining emerging security solutions for vulnerabilities in cyber-physical systems.',
        '2030-05-05',
        '1.2',
        'PUBLISHED',
        '38',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication194',
        210
    ),
    (
        195,
        '195',
        '195',
        'Digital Health',
        'TOPIC_195',
        'Telemedicine: Transforming Healthcare Delivery',
        'Evaluation of telemedicine technologies transforming healthcare delivery systems.',
        '2030-05-21',
        '1.0',
        'DRAFT',
        '34',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication195',
        190
    ),
    (
        196,
        '196',
        '196',
        'Information Systems',
        'TOPIC_196',
        'Blockchain Security: Threats and Countermeasures',
        'Assessing threats in blockchain ecosystems and developing countermeasures.',
        '2030-06-10',
        '1.1',
        'SUBMITTED',
        '46',
        'English',
        'CC BY 4.0',
        'https://example.com/publication196',
        230
    ),
    (
        197,
        '197',
        '197',
        'Astrobiology',
        'TOPIC_197',
        'Life Beyond Earth: Astrobiological Explorations',
        'Exploring the scientific quests for life beyond Earth in the field of astrobiology.',
        '2030-06-27',
        '1.3',
        'UNDER_REVIEW',
        '47',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication197',
        290
    ),
    (
        198,
        '198',
        '198',
        'Digital Transformation',
        'TOPIC_198',
        'Business Models in the Digital Era',
        'An overview of evolving business models due to digital transformation.',
        '2030-07-14',
        '2.0',
        'ACCEPTED',
        '44',
        'English',
        'CC BY-NC 4.0',
        'https://example.com/publication198',
        180
    ),
    (
        199,
        '199',
        '199',
        'Theoretical Physics',
        'TOPIC_199',
        'Multiverse Theories: Perspectives and Predictions',
        'Research into theoretical perspectives and predictions surrounding multiverse theories.',
        '2030-07-30',
        '1.0',
        'PUBLISHED',
        '50',
        'English',
        'CC BY 4.0',
        'https://example.com/publication199',
        310
    ),
    (
        200,
        '200',
        '200',
        'Cybernetics',
        'TOPIC_200',
        'Human-Machine Symbiosis: Frontier Technologies',
        'Integrating frontier technologies for a symbiotic relationship between humans and machines.',
        '2030-08-18',
        '1.1',
        'DRAFT',
        '48',
        'English',
        'CC BY-SA 4.0',
        'https://example.com/publication200',
        225
    );